HMCL/src/main/java/org/jackhuang/hellominecraft/launcher/ui/modpack/ModpackInitializationPanel.java

Fixed the support to Chinese(simplified) characters\hyphen\dot

Fixed the name rule of a mod pack.

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/LaunchingUIDaemon.java
HMCL/src/main/java/org/jackhuang/hmcl/util/Log4jHandler.java

Fix "java.io.IOException: Read end dead" when different Threads are writing to a single PipedOutputStream

Fix "java.io.IOException: Read end dead"

---

HMCLCore/src/main/java/org/jackhuang/hmcl/task/FileDownloadTask.java
HMCLCore/src/main/java/org/jackhuang/hmcl/util/FileUtils.java

#265 
[StackOverFlow](https://stackoverflow.com/questions/14651567/java-file-renameto-does-rename-file-but-returns-false-why)

Fix `Unable move temp file`

---

HMCL/src/main/java/org/jackhuang/hmcl/game/LauncherHelper.java
HMCL/src/main/java/org/jackhuang/hmcl/setting/VersionSetting.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/VersionSettingsController.java
HMCLCore/src/main/java/org/jackhuang/hmcl/util/JavaVersion.java

自动检测 `/usr/lib/jvm` 下的 Java，这是 Java 的通常安装位置（至少在 Debian/Ubuntu 上）。

Linux下自动检测Java + 允许多个相同版本的JRE

---

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/authlibinjector/AuthlibInjectorAccountFactory.java
HMCLCore/src/main/java/org/jackhuang/hmcl/auth/yggdrasil/YggdrasilAccountFactory.java

引入：https://github.com/huanghongxun/HMCL/commit/6c4231a6b242c2a11af9768e424593cc6cc14bc5#diff-839dd42e51cd641828b00c5302c02b12R50

修复YggdrasilAccount读取到了错误的character

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/AddAccountPane.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/AddAuthlibInjectorServerPane.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/Decorator.java
HMCL/src/main/resources/assets/css/root.css
HMCLCore/src/main/java/org/jackhuang/hmcl/auth/authlibinjector/AuthlibInjectorDnD.java

https://github.com/yushijinhun/authlib-injector/wiki/%E5%90%AF%E5%8A%A8%E5%99%A8%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83#dnd-%E6%96%B9%E5%BC%8F%E6%B7%BB%E5%8A%A0-yggdrasil-%E6%9C%8D%E5%8A%A1%E7%AB%AF

支持 DnD 方式添加验证服务器

---

HMCLCore/src/main/java/org/jackhuang/hmcl/download/BMCLAPIDownloadProvider.java

@bangbang93 在 BMCLAPI 上做了 authlib-injector 下载的镜像：https://bmclapidoc.bangbang93.com/#api-Mirrors-Mirrors_authlib_injector

支持从 BMCLAPI 下载 authlib-injector

---

HMCL/src/main/java/org/jackhuang/hmcl/setting/Profile.java
HMCL/src/main/java/org/jackhuang/hmcl/setting/Settings.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/ProfilePage.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/SettingsPage.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/FileItem.java
HMCL/src/main/resources/assets/fxml/profile.fxml
HMCL/src/main/resources/assets/lang/I18N.properties
HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

* 新创建的配置文件中，`当前目录`是勾选此配置项的
* 旧配置文件中默认不勾选

添加设置项：若可能，游戏目录使用相对路径

---

HMCL/src/main/java/org/jackhuang/hmcl/game/AccountHelper.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AccountAdvancedListItem.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AccountListItem.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AccountListItemSkin.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AddAccountPane.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/AdvancedListItem.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/AdvancedListItemSkin.java

支持在头像中显示头盔层

---

README.md

1. When you distribute a modified version of the software, you must change the software name or the version number in a reasonable way in order to distinguish it from the original version. \[[under GPLv3, 7(c).](https://github.com/huanghongxun/HMCL/blob/11820e31a85d8989e41d97476712b07e7094b190/LICENSE#L372-L374)\]
The software name and the version number can be edited [here](https://github.com/huanghongxun/HMCL/blob/11820e31a85d8989e41d97476712b07e7094b190/HMCL/src/main/java/org/jackhuang/hmcl/Metadata.java#L31-L32).
2. You must not remove the copyright declaration displayed in the software. \[[under GPLv3, 7(b).](https://github.com/huanghongxun/HMCL/blob/11820e31a85d8989e41d97476712b07e7094b190/LICENSE#L368-L370)\]
Chinese Translation:
1. …

Add additional terms under GPLv3 section 7

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/decorator/DecoratorSkin.java

Fixed #503

---

HMCL/src/main/resources/assets/lang/I18N_zh.properties

i18n: zh: fixup

---

HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/JavaVersion.java

使用 HashMap 对 java -version 的结果进行缓存以减少不必要的调用

---

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/authlibinjector/AuthlibInjectorServer.java

see yushijinhun/authlib-injector#78

[authlib-injector] forbid multiple ALI redirects

---

HMCL/src/main/java/org/jackhuang/hmcl/Main.java
HMCL/src/main/java/org/jackhuang/hmcl/util/SelfDependencyPatcher.java
build.gradle

Copy from [Recaf](https://github.com/Col-E/Recaf) to fix https://github.com/huanghongxun/HMCL/issues/509

Compatible with JVM environment without Javafx 

---

HMCL/build.gradle

没法测签名的问题，不过 duplicated entries 的问题是解决了。

Remove shadowJar.

---

HMCL/src/main/java/org/jackhuang/hmcl/Main.java
HMCL/src/main/java/org/jackhuang/hmcl/util/SelfDependencyPatcher.java
HMCL/src/main/resources/assets/lang/I18N.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties
HMCLCore/src/main/java/org/jackhuang/hmcl/download/MultipleSourceVersionList.java
README.md

目前内置 Maven Central 和阿里云镜像作为源，当 `user.country` 为 `CN` 时默认选中阿里云源，其他时候默认选择 Maven Central 源。
也可以使用 `-Dhmcl.openjfx.repo` 添加额外下载源选项，此时自定义源默认被选中。

询问用户是否下载 JavaFX，以及便捷选择下载源

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AccountLoginPane.java

修复重新输入密码弹窗不显示的问题
close #1065
close #1075
close #1072

fix(ui): AccountLoginPane not showing.

---

README.md

根据最近的变化对README下载部分稍作修改

---

HMCLCore/src/main/java/org/jackhuang/hmcl/util/io/Zipper.java

fix(core): zipper lose the file attributes

---

HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java

See: https://github.com/apache/logging-log4j2/pull/614

Actually fixed CVE-2021-44228

---

.github/workflows/check-update.yml

更新 check-update.yml

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/GameCrashWindow.java
HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java

Fix #1247: Parse minecraft startup command when call cmd

---

HMCL/src/main/java/moe/mickey/minecraft/skin/fx/SkinAnimation.java
HMCL/src/main/java/moe/mickey/minecraft/skin/fx/SkinCanvas.java
HMCL/src/main/java/moe/mickey/minecraft/skin/fx/SkinCube.java
HMCL/src/main/java/moe/mickey/minecraft/skin/fx/SkinHelper.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/account/OfflineAccountSkinPane.java

[WIP] Added cape rendering support

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/GameCrashWindow.java

#1340
很多玩家拿着游戏崩溃界面导出问，在界面上显示启动器版本更便于调试。

在游戏崩溃窗口显示 HMCL 版本

---

.github/ISSUE_TEMPLATE/bug-report.yml

更新 bug-report.yml 添加英文注释

---

HMCL/src/main/java/org/jackhuang/hmcl/game/HMCLModpackManager.java
HMCL/src/main/java/org/jackhuang/hmcl/game/ModpackHelper.java
HMCLCore/src/main/java/org/jackhuang/hmcl/mod/curse/CurseManifest.java
HMCLCore/src/main/java/org/jackhuang/hmcl/mod/mcbbs/McbbsModpackManifest.java
HMCLCore/src/main/java/org/jackhuang/hmcl/mod/multimc/MultiMCInstanceConfiguration.java
HMCLCore/src/main/java/org/jackhuang/hmcl/mod/multimc/MultiMCManifest.java
HMCLCore/src/main/java/org/jackhuang/hmcl/mod/server/ServerModpackManifest.java
HMCLCore/src/main/java/org/jackhuang/hmcl/util/io/CompressingUtils.java

见 #1368，JDK 的 zip 实现问题导致无法识别一些整合包。

使用 Commons Compress 处理整合包

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AccountListItem.java

虽然目前难以实现完整的上传功能，但是可以将用户指引至 https://www.minecraft.net/profile/skin 自行上传。

为微软登录显示上传皮肤按钮

---

HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/JavaVersion.java

This is a very draft quality PR. I don't even have JDK installed to build it, that's how draft it is.
1. Refactor function to share common steps of the code: system locations, Minecraft launcher runtimes, PATH/HMCL_JRES
2. Modify Minecraft launcher runtimes to include java-runtime-beta

chore(javaversion): refactor searchPotentialJavaExecutables

---

HMCLCore/src/main/java/org/jackhuang/hmcl/game/JavaVersionConstraint.java
HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/Architecture.java

* 改进 MacOS AArch64 支持
* 提供龙芯的基本支持

适配 Apple Silicon Mac 与龙芯

---

HMCLCore/src/main/java/org/jackhuang/hmcl/download/MaintainTask.java
HMCLCore/src/main/java/org/jackhuang/hmcl/game/VersionLibraryBuilder.java

Fix crash with OptiFine.

---

HMCLCore/src/main/java/org/jackhuang/hmcl/mod/RemoteMod.java

修复curseforge文件名存在中文下载失败

---

HMCLCore/src/main/java/org/jackhuang/hmcl/util/io/CompressingUtils.java

https://paste.ubuntu.com/p/x4KFRNqpm2/

Fix NoSuchMethodError when compiling with Java 9+

---

HMCL/src/main/resources/assets/lang/I18N_zh.properties

修訂了一些台灣詞彙。來自https://discord.com/channels/815819580840607807/815860830058840064/1003644502478704671
RPMTW的翻譯討論頻道。
請不要關閉PR
因為還沒有修訂好！

I18N_zh.properties 繁体中文修订

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/download/AdditionalInstallersPage.java
HMCLCore/src/main/java/org/jackhuang/hmcl/game/DefaultGameRepository.java

源报告：![QA6L5V8@12}@C4{V$9{IFI8](https://user-images.githubusercontent.com/20694662/187048343-79e20d7c-d232-4705-bd40-230f8465eedf.png)

修复通过自动安装更新游戏时的崩溃

---

README.md
README_cn.md

添加了 Quilt 安装功能的介绍，且更改 Mac OS 为 macOS， macOS 为现代 Mac 系统命名。

更新 README 文件

---

HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties
HMCL/src/main/resources/assets/natives.json
PLATFORM.md
javafx.gradle.kts

已完成龙芯 3A4000 平台的 LWJGL2/3 的基本适配。
由于手上没有测试机器，由群友代替测试。游戏基本可玩，但音频存在问题。
暂时没有机器 DEBUG，等收一台龙芯 3A4000 测试机再说。

添加 Linux MIPS64el 平台支持

---

HMCLCore/src/main/java/org/jackhuang/hmcl/mod/modrinth/ModrinthCompletionTask.java

fix https://github.com/huanghongxun/HMCL/issues/1701

fix modrinth modpack install

---

HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java
HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/SystemUtils.java

Fix #1736: 修复执行 PreLaunchCommand 时会被阻塞的问题

---

HMCL/src/main/java/org/jackhuang/hmcl/Metadata.java
HMCL/src/main/java/org/jackhuang/hmcl/game/OAuthServer.java
HMCLCore/src/main/java/org/jackhuang/hmcl/mod/curse/CurseForgeRemoteModRepository.java
HMCLCore/src/main/java/org/jackhuang/hmcl/util/io/JarUtils.java

在 JarUtils 中缓存 Manifest

---

.github/workflows/check-update.yml
HMCL/src/main/java/org/jackhuang/hmcl/Metadata.java

https://github.com/huanghongxun/HMCL-docs/pull/23
这样可以提交修改来方便更新 changelog

将日志更换至docs.hmcl.net

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/multiplayer/MultiplayerManager.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/multiplayer/MultiplayerPage.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/multiplayer/MultiplayerPageSkin.java
HMCL/src/main/resources/assets/lang/I18N.properties
HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

* 显示索引码到期时间；
* HiPer 文件缺失或无法通过验证时自动重新下载。

完善 HiPer 支持

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/account/CreateAccountPane.java

修复微软账户登录弹窗不显示“忘记密码”的问题

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/UpgradeDialog.java
HMCL/src/main/java/org/jackhuang/hmcl/upgrade/UpdateChecker.java

https://github.com/huanghongxun/HMCL-docs/pull/29

在HMCL显示changelog时自动定位该更新内容

---

HMCL/build.gradle.kts

修改非主线仓库中 GitHub Action 构建的版本号

---

HMCL/src/main/java/org/jackhuang/hmcl/setting/VersionSetting.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/VersionIconDialog.java

同时修改了VersionSetting 的反序列化函数，为以后给选项添加其他值做准备，防止因为索引溢出而反序列化失败。

将 Quilt 图标添加至 VersionIconDialog

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModListPageSkin.java

回滚 Mod 时隐藏弹出菜单

---

HMCL/src/main/resources/assets/HMCLauncher.sh
HMCLauncher/HMCL/main.cpp

https://github.com/huanghongxun/HMCL-docs/pull/36/

exe and sh download java link update

---

HMCL/src/main/java/org/jackhuang/hmcl/game/HMCLGameRepository.java
HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java
HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/CommandBuilder.java

* 修复整合包参数覆盖游戏设置的问题
* 调整了默认 JVM 参数，与官启保持一致
* 将 `G1HeapRegionSize` 从 16m 调整至 32m
* 删除默认生成的 `-Xmn` 选项
熬夜写的，简单测试了一下没遇到问题，希望 Review 的时候能认真帮忙看看，怕神志不清写出了啥问题。

Adjust JVM arguments priority

---

HMCL/src/main/java/org/jackhuang/hmcl/upgrade/ExecutableHeaderHelper.java

fix crash on Java 8

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml

- 发送 Bug Feedback 时会附上 bug 标签
- 调整 Bug Feedback 中的问题描述输入框的位置，并将其设为必填项
- 添加 QQ 频道反馈

改进 Github Issue 模板

---

HMCLCore/src/main/java/org/jackhuang/hmcl/mod/FabricModMetadata.java
HMCLCore/src/main/java/org/jackhuang/hmcl/mod/ForgeNewModMetadata.java
HMCLCore/src/main/java/org/jackhuang/hmcl/mod/ForgeOldModMetadata.java
HMCLCore/src/main/java/org/jackhuang/hmcl/mod/ModManager.java
HMCLCore/src/main/java/org/jackhuang/hmcl/mod/PackMcMeta.java

优化 mod 列表加载速度

---

HMCL/src/main/java/org/jackhuang/hmcl/game/HMCLGameRepository.java
HMCLCore/src/main/java/org/jackhuang/hmcl/game/LaunchOptions.java
HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java

fix #1999: Add overrideJavaArguments to LaunchOptions

---

javafx.gradle.kts

Bump OpenJFX from 17.0.2 to 19.0.2.1

---

HMCL/src/main/java/org/jackhuang/hmcl/game/TexturesLoader.java

在 `GraphicsContext` 不支持 `setImageSmoothing` 时，使用最近邻插值算法直接通过 `PixelWriter` 绘制图像。
这样可以避免从 JavaFX `Image` 复制至 Java2D `BufferedImage` 再复制回来的开销，也减少了对 Java 2D 的依赖。
本 PR 对大部分用户没有任何影响，因为 JavaFX 12+ 或者不太老的 Java 8 都直接支持了 `setImageSmoothing`，不会使用这个后备方案。

Remove drawAvatarJ2D

---

HMCL/src/main/resources/assets/lang/I18N.properties
HMCL/src/main/resources/assets/lang/I18N_es.properties
HMCL/src/main/resources/assets/lang/I18N_ja.properties
HMCL/src/main/resources/assets/lang/I18N_ru.properties
HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

添加翻译键：modrinth.category.datapack

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModListPage.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModListPageSkin.java
HMCL/src/main/java/org/jackhuang/hmcl/util/Debouncer.java

close #2043: Make ModListPage searchable

---

HMCL/src/main/resources/assets/natives.json
PLATFORM.md

已在 StarFive VisionFive 2 上进行了测试，运行情况良好。

添加 Linux RISC-V 64 平台支持

---

HMCL/src/main/java/org/jackhuang/hmcl/setting/Config.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/main/MainPage.java

现在新加一条提示就得多一组条目，改起来麻烦而且 Config 膨胀的太厉害，这里改成用一个 Map 聚合存储所有提示。

优化 Config 存储方式

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/GameCrashWindow.java

游戏崩溃窗口添加 物理内存大小 显示项

---

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/yggdrasil/YggdrasilService.java

Update PURCHASE_URL and MIGRATION_FAQ_URL

---

HMCLCore/src/main/java/org/jackhuang/hmcl/mod/ModLoaderType.java
HMCLCore/src/main/java/org/jackhuang/hmcl/mod/curse/CurseAddon.java
HMCLCore/src/main/java/org/jackhuang/hmcl/mod/modrinth/ModrinthRemoteModRepository.java

Support #2299 Add support to ModLoaderType.QUILT

---

HMCL/src/main/resources/assets/lang/I18N.properties
HMCL/src/main/resources/assets/lang/I18N_es.properties
HMCL/src/main/resources/assets/lang/I18N_ja.properties
HMCL/src/main/resources/assets/lang/I18N_ru.properties
HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

添加了Modrinth分类“Folia”的翻译键。

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/DownloadPage.java

Close #2284 
Render supported mod loader in org.jackhuang.hmcl.ui.versions.DownloadPage.ModItem.

Support #2284 在 ModItem 中渲染所支持的加载器

---

HMCL/src/main/java/org/jackhuang/hmcl/setting/Config.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/LogWindow.java

将配置文件的 logLines 键默认值改为 1000

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/DownloadPage.java

- 修复 VersionType 图标
- 补充 Quilt 标签

改进 ModItem 中渲染 ModLoaderType 的代码

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/GameCrashWindow.java

Fix checkstyle @huanghongxun 请尽快 merge
Fix #2314

Fix #2314 / Redundant import in GameCrashWindow

---

HMCLCore/src/main/java/org/jackhuang/hmcl/mod/RemoteModRepository.java

修复搜索栏处的版本顺序错误

---

HMCL/src/main/java/org/jackhuang/hmcl/game/HMCLGameLauncher.java

Fix #2305 修复游戏语言自动切换功能与不同版本的兼容性问题

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/LogWindow.java

Close #2128 
现在，你可以通过 ctrl 来选中多个日志，随后按下 ctrl+c 来复制

Support #2128 LogWindow 可复制

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/LogWindow.java

This reverts commit 9a59ca95a1ac53072dbf48ed6e27be42d48129a2.

Revert "Support copy action in LogWindow (#2351)"

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/VersionPage.java
HMCL/src/main/resources/assets/lang/I18N.properties
HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

可以打开logs文件夹
更改了shaderpacks文件夹的图标

add logs folder open and change the shaderpacks icon

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/LogWindow.java
HMCL/src/main/resources/assets/css/root.css

Support2128 log window copy able

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModUpdatesPage.java
HMCLCore/src/main/java/org/jackhuang/hmcl/util/InfiniteSizeList.java
HMCLCore/src/main/java/org/jackhuang/hmcl/util/io/CSVTable.java

会生成类似于 https://gist.github.com/burningtnt/d5c8afbd999422f06fb9e22d3d85eaf1 的文件
Close #2010

Support  #2010 一键导出待更新模组列表

---

HMCL/src/main/java/org/jackhuang/hmcl/setting/VersionSetting.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/AdvancedVersionSettingPage.java
HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java
HMCLCore/src/main/java/org/jackhuang/hmcl/util/StringUtils.java

Fix 2338 自定义命令问题

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AccountListItemSkin.java
HMCL/src/main/resources/assets/lang/I18N.properties
HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

Support #1547 Support copying the UUID of the account

---

HMCL/src/main/java/org/jackhuang/hmcl/util/FractureiserDetector.java

Fix #2397 Fractureiser 检测没有判断是否为文件

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModUpdatesPage.java
HMCLCore/src/main/java/org/jackhuang/hmcl/util/InfiniteSizeList.java

Fix #2444 NPE while exporting the mod list which is going to be updated.

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/GameCrashWindow.java
HMCLCore/src/main/java/org/jackhuang/hmcl/game/CrashReportAnalyzer.java
HMCLCore/src/test/java/org/jackhuang/hmcl/game/CrashReportAnalyzerTest.java

Support #2416 Enable HMCL to analyze crash reasons from latest.log

---

HMCLCore/src/main/java/org/jackhuang/hmcl/util/Hex.java
HMCLCore/src/test/java/org/jackhuang/hmcl/util/HexTest.java

针对 Hex 的微优化，对 Java 9+ 大概有 10% 的性能提升，并且略微降低内存占用，

Optimization for Hex

---

HMCL/src/main/java/org/jackhuang/hmcl/countly/CrashReport.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/CrashWindow.java
HMCL/src/main/java/org/jackhuang/hmcl/util/CrashReporter.java
HMCL/src/main/resources/assets/lang/I18N.properties
HMCL/src/main/resources/assets/lang/I18N_es.properties
HMCL/src/main/resources/assets/lang/I18N_ja.properties
HMCL/src/main/resources/assets/lang/I18N_ru.properties
HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

在出现 InternalError 的时候提示用户 Java 损坏

Catch Internal Error

---

HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java

~有人没有用 try-with-source 写，我不说是谁~

Fix DefaultLauncher

---

HMCL/build.gradle.kts

更轻（减少 50KB）

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature.yml

主要对 Bug Feedback 模板做了修改，删去了游戏崩溃相关的内容，并引导游戏崩溃问题去 KOOK 或 Discord 反馈。

[Enhance] Enhance issue templates 改进 Issue 模板

---

HMCLCore/src/main/java/org/jackhuang/hmcl/util/StringUtils.java
HMCLCore/src/test/java/org/jackhuang/hmcl/util/TokenizerTest.java

Fix string tokenizer

---

HMCL/src/main/java/org/jackhuang/hmcl/setting/ConfigHolder.java
HMCL/src/main/java/org/jackhuang/hmcl/setting/ConfigUpgrader.java

造个轮子，防止类似于 #2271 这样改了 Config 但没有 DFU 的情况再次发生，并极略微优化了启动时的性能（干掉了一堆 lambda 的初始化）。

Build configuration DFU system.

---

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/microsoft/MicrosoftAccount.java

auth: Always check token.exp when launch game

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModListPageSkin.java

本地模组管理界面中，点击搜索按钮后自动将光标定位到输入框 Close #2643

Support #2643

---

HMCL/src/main/java/org/jackhuang/hmcl/game/HMCLGameLauncher.java
HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java

version::compareTo compares the name of thihs version instead of the game version.

Fix: version::compareTo compares the name, instead of the game version.

---

HMCLCore/src/main/java/org/jackhuang/hmcl/mod/RemoteMod.java

Render required dependencies first.

---

HMCLCore/src/main/java/org/jackhuang/hmcl/download/MojangDownloadProvider.java
HMCLCore/src/main/java/org/jackhuang/hmcl/download/neoforge/NeoForgeOfficialVersionList.java

Support downloading NeoForge from official maven.

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/download/AdditionalInstallersPage.java

#2726 导致 `AdditionalInstallersPage` 的 `reload` 发生损坏。

修复 AdditionalInstallersPage

---

HMCLCore/src/main/java/org/jackhuang/hmcl/game/CrashReportAnalyzer.java
HMCLCore/src/test/java/org/jackhuang/hmcl/game/CrashReportAnalyzerTest.java
HMCLCore/src/test/resources/logs/fabric_warnings3.txt

Update Fabric warnings pattern in CrashReportAnalyzer

---

.github/workflows/check-update.yml

Fix check-update.yml

---

HMCLCore/src/main/java/org/jackhuang/hmcl/mod/modinfo/ForgeNewModMetadata.java

Fix 2774: Local NeoForge mods shouldn't be identified as Forge mods.

---

HMCLCore/src/main/java/org/jackhuang/hmcl/util/InvocationDispatcher.java

原版读起来有点太弯绕了，内联一下 lambda 以改善可读性

简化 InvocationDispatcher

---

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/microsoft/MicrosoftAccount.java

Revert "auth: Always check token.exp when launch game"

---

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/microsoft/MicrosoftAccount.java

This reverts commit 8678c0dcf2af0c0d13f7e0ef4417a4fef88bd564.

Revert "auth: Always check token.exp when launch game (#2642)"

---

HMCLCore/src/main/java/org/jackhuang/hmcl/task/FetchTask.java
HMCLCore/src/main/java/org/jackhuang/hmcl/util/io/NetworkUtils.java

Close #2911: 下载失败时打印重定向链

---

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/authlibinjector/AuthlibInjectorDownloader.java
HMCLCore/src/main/java/org/jackhuang/hmcl/auth/microsoft/MicrosoftService.java

Fix Microsoft authentication

---

HMCLCore/src/main/java/org/jackhuang/hmcl/util/io/FileUtils.java

增加对 Cinnamon 桌面的支持

---

HMCL/src/main/java/org/jackhuang/hmcl/game/LauncherHelper.java
HMCLCore/src/main/java/org/jackhuang/hmcl/game/JavaVersionConstraint.java

支持自动下载 Java 21

---

HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/JavaVersion.java

Closes #3033
虽然brew支持Linux，但是讲道理没人会在Linux用吧……

fix: support java from homebrew

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/VersionPage.java
HMCLCore/src/main/java/org/jackhuang/hmcl/game/DefaultGameRepository.java

Fix #3026: resources 目录应该跟随游戏目录

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/DownloadPage.java

Fix #3086 修复模组下载界面版本推荐功能

---

HMCLCore/src/main/java/org/jackhuang/hmcl/download/forge/ForgeBMCLVersionList.java

修复 #3131 1.7.10-pre4 版本 Forge 安装问题

---

HMCLCore/src/main/java/org/jackhuang/hmcl/download/forge/ForgeBMCLVersionList.java

Fix #3135 
Forge 特色。这个版本必须是 prerelease

修复 #3135 Forge 1.7.10-pre4 安装问题（2）

---

HMCLCore/src/main/java/org/jackhuang/hmcl/download/neoforge/NeoForgeOfficialVersionList.java

[重要] 修复 #3127 1.21 NeoForge 下载问题

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/DownloadPage.java

修复 #3112 模组详情中若没有这个游戏版本，仍然会出现该下拉栏的问题

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/DownloadListPage.java
HMCLCore/src/main/java/org/jackhuang/hmcl/mod/curse/CurseForgeRemoteModRepository.java
HMCLCore/src/main/java/org/jackhuang/hmcl/mod/modrinth/ModrinthRemoteModRepository.java

优化大量代码，并修复了一堆 Bug
Fix #3065 Fix #3148

Fix #3065: 修复 CurseForge 搜索 API 对翻页总量计算不正确的 Bug

---

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/microsoft/MicrosoftService.java

[重要] 实现 #3095 微软登录界面对 XBox 400 错误给予提示

---

HMCLCore/src/main/java/org/jackhuang/hmcl/download/MojangDownloadProvider.java
HMCLCore/src/main/java/org/jackhuang/hmcl/download/forge/ForgeVersionList.java

Revert "支持 Forge 官方源"

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModListPageSkin.java

[测试模组（zip -> jar）](https://github.com/user-attachments/files/16578159/animatica-0.6.1%2B1.20.4.zip)

修复模组详情页图标问题

---

HMCLCore/src/main/java/org/jackhuang/hmcl/download/forge/ForgeVersion.java
HMCLCore/src/main/java/org/jackhuang/hmcl/download/forge/ForgeVersionList.java

显示 Forge 发版时间

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/FXUtils.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModListPageSkin.java

https://github.com/user-attachments/assets/748d323b-6ad1-430d-9d3f-ad8fba4cd410

支持在 Linux 或 BSD 中使用 showFileInExplorer

---

HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/JavaVersion.java

在 Linux 系统支持从 ~/.sdkman/candidates/java 查找 Java（应该不会有人改安装目录或者拿别的系统安装 SDKMAN! 吧）
Close #3043

[Feature] Supported JRE from SDKMAN! on Linux

---

HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/JavaVersion.java

Fix checkstyle bug in #3062.
I do not know why, but this also affected my PR: https://github.com/HMCL-dev/HMCL/actions/runs/10934605359

Fix checkstyle

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/InstallerListPage.java

Close #3208

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/DownloadPage.java

下载页面的下载项目图标会根据版本自动调整

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AccountListItemSkin.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AccountListPage.java

https://github.com/user-attachments/assets/2f70b3ce-65b6-4b8c-853d-f1c2c35e92ed
Close #1596

删除账户和删除认证服务器时弹出提示确认删除

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/main/MainPage.java

不太会搞这个更新弹窗展示，如果可以就帮一下（
https://github.com/HMCL-dev/HMCL/issues/3281

发现更新弹窗添加取消按钮

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/download/InstallersPage.java
HMCLCore/src/main/java/org/jackhuang/hmcl/download/LibraryAnalyzer.java

https://github.com/user-attachments/assets/1c9a7596-68da-42ff-9048-a27569dfb7b6
Close #2697

安装新版本的版本名输入框显示已选择加载器名称

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModListPageSkin.java

按 Enter 真的很烦（
https://github.com/user-attachments/assets/31877126-7e5d-4871-aeea-604369038c11

模组管理搜索操作更改为文本更新后触发

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/main/AboutPage.java
HMCL/src/main/resources/assets/about/deps.json
HMCL/src/main/resources/assets/about/thanks.json

从 JSON 文件中加载“关于”页面中“鸣谢”和“依赖”的内容，降低维护成本。

优化 AboutPage

---

HMCL/src/main/java/org/jackhuang/hmcl/game/LauncherHelper.java

This problem is almost unnoticeable when using Chinese, but very obvious when using English - this PR fixes it.

Fix some error message wrap

---

HMCL/src/main/java/org/jackhuang/hmcl/game/LauncherHelper.java
HMCL/src/main/resources/assets/lang/I18N.properties
HMCL/src/main/resources/assets/lang/I18N_es.properties
HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

Although the site automatically redirects, I chose to fix it.

Fix some link

---

HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

Part 1, the content before `game.crash`.
*Some revisions from #2461.*
Others:
- #3346
- #3348
- #3349

Revise zh_CN part 1

---

HMCL/src/main/resources/assets/lang/I18N_zh.properties

cc @Glavo @burningtnt @zkitefly
Others:
- #3356
- #3357
- #3358

Revise zh_TW part 4

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/WorldInfoPage.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/WorldListItem.java
HMCL/src/main/resources/assets/lang/I18N.properties
HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

优化 WorldInfoPage

---

README.md

修改了英文版的readme.md，并未增加或删除内容，只是让一些句子更加自然了一些

略微修改了一下英文版的readme.md

---

README.md
README_cn.md
README_tw.md

- Change some badge links to the currently used links
- Revise Chinese readme
When merging this, consider merging #3354 as well.

Revise readme

---

HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

- When choosing a download source, the commas in the BMCLAPI item are changed to half-width.
- Remove extra line breaks in the home page hint.

zh_CN Post-fix

---

HMCL/src/main/resources/assets/lang/I18N.properties
HMCL/src/main/resources/assets/lang/I18N_es.properties
HMCL/src/main/resources/assets/lang/I18N_ja.properties
HMCL/src/main/resources/assets/lang/I18N_ru.properties
HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

- Update copyright year
- Unify typesetting style

Adjust language file header comments

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/account/CreateAccountPane.java

The original link is no longer available. Change to the link provided by Microsoft.

Change forgot password link

---

HMCL/src/main/resources/assets/lang/I18N_es.properties
HMCL/src/main/resources/assets/lang/I18N_ja.properties
HMCL/src/main/resources/assets/lang/I18N_ru.properties

Adjust Java management i18n

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/FXUtils.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/GameCrashWindow.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/TooltipInstaller.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/account/CreateAccountPane.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/main/MainPage.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/main/RootPage.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/DownloadListPage.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/DownloadPage.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/GameListItemSkin.java
HMCLCore/src/main/java/org/jackhuang/hmcl/java/JavaInfo.java

* 避免每次调用时进行反射和捕获异常
* 移除不必要的 `runInFX` 调用

优化 FXUtils.installTooltip

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModListPageSkin.java

https://github.com/user-attachments/assets/0671556f-1705-4356-897d-c41a5074e8ab

模组管理添加右键查看模组详情

---

HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

I forgot to change the zh_CN part. A half-width colon is better.

Adjust custom command hint (zh_CN only)

---

PLATFORM.md
README.md

README & PLATFORM docs post-fixes

---

HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

Fix extra "=" in zh_CN `launch.advice` translation

---

HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

- Simplified Chinese only
- Minor revision
Oops...

Revise Chinese

---

HMCL/src/main/resources/assets/lang/I18N.properties

- Adjust some translation styles again
- Fix some missed mistakes
Hopefully this is the last revision :/

Revise English

---

HMCLCore/src/main/java/org/jackhuang/hmcl/mod/modinfo/ForgeNewModMetadata.java

Fix #3460 无法识别奇异的 Forge (Like) 模组 Metadata

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/UpgradeDialog.java

Fix #3456 在更新预览界面没法拖动启动器窗口

---

.github/workflows/check-update.yml

gha: revise release description [skip ci]

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/MDListCell.java

Fix #3063 修复本地模组管理界面水平滚动条显示异常的问题

---

README.md
README_cn.md
README_tw.md

ref: https://shields.io/blog/simple-icons-14

Fix qq badge in readme

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/DownloadPage.java
HMCL/src/main/java/org/jackhuang/hmcl/util/i18n/I18n.java
HMCL/src/main/java/org/jackhuang/hmcl/util/i18n/Locales.java
HMCL/src/main/resources/assets/lang/I18N.properties
HMCL/src/main/resources/assets/lang/I18N_es.properties
HMCL/src/main/resources/assets/lang/I18N_ja.properties
HMCL/src/main/resources/assets/lang/I18N_ru.properties
HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

- unify time formats using DateTimeFormatter, deprecate `world.time`
- change FormatStyle to make the time detail appropriate
- fix incorrect time format in English locale

improv(i18n): refine time formats on ui

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/download/VersionsPage.java

优化 VersionsPage 搜索框

---

HMCL/src/main/resources/assets/lang/I18N_ru.properties

- Re-translate some translations based on English
- Fix some inconsistent terminology
- Such as `Account`, `учетная запись` > `аккаунт`
- Add some missing translations
- Reorder some keys to ensure they match with English
- Adjust terminology related to LittleSkin to ensure consistency with the terminology used on the site

chore(locale): improve russian translation (account part)

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/decorator/DecoratorController.java

https://github.com/user-attachments/assets/c0a5136b-5519-4c68-bbc3-6e5eeea7767a

添加关闭启动器时的淡出动画

---

HMCL/src/main/resources/assets/lang/I18N_ru.properties

- add `unofficial.hint`
- fix typo in `account.methods.microsoft.snapshot`

chore(locale): revise unofficial hint for russian

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/FXUtils.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/VersionSettingsPage.java

清理 FXUtils

---

HMCL/src/main/resources/assets/lang/I18N_ru.properties

- add `mods.check_updates.empty`
- add nbt translations

chore(locale): improve russian translation (mods & nbt)

---

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/yggdrasil/YggdrasilService.java

更新 PURCHASE_URL

---

HMCL/src/main/java/org/jackhuang/hmcl/Main.java

Revert "启用高帧率动画"

---

HMCL/src/main/resources/assets/lang/I18N.properties

My mistake in https://github.com/HMCL-dev/HMCL/pull/3367

fix(locale): fix english translation of `game.crash.reason.file_changed`

---

HMCL/src/main/resources/assets/lang/I18N_es.properties

- Add translation of the `game.crash` part.
- Improve further the translation of the remaining parts.

chore(locale): improve spanish translation

---

HMCL/src/main/resources/assets/lang/I18N_es.properties

fix(locale): revise spanish

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/UpgradeDialog.java

Close #3728: 为更新日志对话框添加平滑滚动

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/AdvancedVersionSettingPage.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/WorldInfoPage.java

突然意识到为什么有些页面看着这么奇怪了，原来是没加半透明的遮罩。

为部分页面添加半透明背景遮罩

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/HTMLRenderer.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/UpgradeDialog.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/WebPage.java

HTMLRenderer 应当避免插入过多换行符

---

HMCLCore/src/main/java/org/jackhuang/hmcl/util/io/IOUtils.java
HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/Architecture.java

Fix #3777: 修复使用 Rosetta 2 转译运行时无法正确识别系统架构的问题

---

HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

Fix #3589 Minecraft Wiki 链接错误

---

HMCL/src/main/resources/assets/lang/I18N_es.properties

Replace the quotation marks with guillemets.

chore(locale): adjust the use of quotation marks in spanish

---

HMCLCore/src/main/java/org/jackhuang/hmcl/download/liteloader/LiteLoaderBMCLVersionList.java
HMCLCore/src/main/java/org/jackhuang/hmcl/download/liteloader/LiteLoaderRemoteVersion.java
HMCLCore/src/main/java/org/jackhuang/hmcl/download/liteloader/LiteLoaderVersionList.java

Fix #3147 修复 LiteLoader 下载相关问题

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/export/ModpackTypeSelectionPage.java

统一导出和导入整合包页面样式

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/HMCLLocalizedDownloadListPage.java

#3829: 将模组/整合包/资源包的默认下载源调整为 Modrinth

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/main/MainPage.java

右键主页“启动游戏”按钮时展开版本列表菜单

---

HMCL/src/main/resources/assets/lang/I18N_es.properties
HMCL/src/main/resources/assets/lang/I18N_ru.properties

For relevant text of offline account restrictions.

chore(locale): add new translations for russian and spanish

---

.gitignore
HMCL/src/main/java/org/jackhuang/hmcl/Launcher.java
HMCL/src/main/java/org/jackhuang/hmcl/Main.java
HMCL/src/main/java/org/jackhuang/hmcl/Metadata.java
HMCL/src/main/java/org/jackhuang/hmcl/game/TexturesLoader.java
HMCL/src/main/java/org/jackhuang/hmcl/java/JavaManager.java
HMCL/src/main/java/org/jackhuang/hmcl/setting/Accounts.java
HMCL/src/main/java/org/jackhuang/hmcl/setting/ConfigHolder.java
HMCL/src/main/java/org/jackhuang/hmcl/setting/Theme.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/decorator/DecoratorController.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/main/SettingsView.java
HMCL/src/main/java/org/jackhuang/hmcl/upgrade/UpdateHandler.java
HMCL/src/main/java/org/jackhuang/hmcl/util/SelfDependencyPatcher.java
HMCL/src/main/resources/assets/lang/I18N.properties
HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

该 PR 会在用户工作路径下创建 `.hmcl` 文件夹存放以下文件：
* `hmcl.json`
* 日志
* 背景图片
* `authlib-injector.jar`

使用工作路径下的 .hmcl 文件夹存放所有配置文件

---

HMCL/src/main/resources/assets/lang/I18N.properties
HMCL/src/main/resources/assets/lang/I18N_es.properties
HMCL/src/main/resources/assets/lang/I18N_ru.properties
HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

Cool! They added a special category for Twilight Forest...

fix(locale): add i18n key curse.category.7669

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/download/DownloadPage.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/download/ModpackSelectionPage.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/Versions.java

Fix #3852 修复无法一键更新整合包

---

HMCL/src/main/java/org/jackhuang/hmcl/Metadata.java

更新 GROUPS_URL

---

HMCLCore/src/main/java/org/jackhuang/hmcl/download/BMCLAPIDownloadProvider.java

更换 unlisted-versions-of-minecraft 镜像源

---

.github/workflows/check-codes.yml
build.gradle.kts

新增一个 `checkstyle` 任务作为同时调用 `checkstyleMain` 和 `checkstyleTest` 的简写。

创建 checkstyle task

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AccountListItem.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AccountListItemSkin.java

Fix #4158 : 禁用非官方版的现有微软账户的刷新选项

---

HMCLCore/src/main/java/org/jackhuang/hmcl/util/io/CompressingUtils.java
HMCLCore/src/main/java/org/jackhuang/hmcl/util/tree/ArchiveFileTree.java
HMCLCore/src/main/java/org/jackhuang/hmcl/util/tree/ZipFileTree.java
HMCLCore/src/test/java/org/jackhuang/hmcl/util/tree/ZipFileTreeTest.java

为了替代掉 ZipFileSystem，我们需要进一步丰富 ArchiveFileTree 的功能。

优化 ArchiveFileTree

---

HMCL/src/main/resources/assets/lang/I18N_es.properties
HMCL/src/main/resources/assets/lang/I18N_ru.properties

follows https://github.com/HMCL-dev/HMCL/pull/3205 and https://github.com/HMCL-dev/HMCL/pull/4184

chore(locale): port background option translation to es and ru

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/download/ModpackInstallWizardProvider.java

修复整合包格式不匹配提示未被正确格式化的问题

---

HMCLCore/src/main/java/org/jackhuang/hmcl/download/DefaultCacheRepository.java
HMCLCore/src/main/java/org/jackhuang/hmcl/util/CacheRepository.java

Fix 4232: 修复初始化 CacheRepository 导致启动器崩溃的问题

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/download/VersionsPage.java

修复部分版本 wiki 链接不正确

---

HMCLCore/src/main/java/org/jackhuang/hmcl/download/neoforge/NeoForgeBMCLVersionList.java
HMCLCore/src/main/java/org/jackhuang/hmcl/download/neoforge/NeoForgeOfficialVersionList.java
HMCLCore/src/main/java/org/jackhuang/hmcl/download/neoforge/NeoForgeRemoteVersion.java

为Neoforge下载添加正式版/快照分类

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/TaskListPane.java

修复 TaskListPane 未正确处理 StagesHintTask 的问题

---

HMCL/src/main/java/org/jackhuang/hmcl/util/ChunkBaseApp.java

https://github.com/HMCL-dev/HMCL/pull/4274

[release/3.6] 修复 1.21.5 以上的地图跳转种子地图错误

---

HMCL/src/main/resources/assets/css/root.css

HintPane 使用新版 Bootstrap 调色盘

---

HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

and have a fix in zh-tw
resolves https://github.com/HMCL-dev/HMCL/issues/4374

chore(l10n): change translation from 版本 to 实例 in zh-cn for term INSTANCE

---

HMCLCore/src/main/java/org/jackhuang/hmcl/download/game/GameRemoteVersion.java

https://github.com/HMCL-dev/HMCL/pull/4066
https://github.com/HMCL-dev/HMCL/pull/4244

[release/3.6] 修复游戏版本列表错误地过滤掉部分版本的问题

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/decorator/DecoratorController.java

https://github.com/HMCL-dev/HMCL/pull/4437

[release/3.6] 修复 backgroundType 为 null 时启动器崩溃的问题

---

HMCL/src/main/resources/assets/mod_data.txt
HMCL/src/main/resources/assets/modpack_data.txt

https://github.com/HMCL-dev/HMCL/pull/4439

[release/3.6] 更新模组和整合包数据

---

HMCL/src/main/resources/assets/css/root.css

https://github.com/HMCL-dev/HMCL/pull/4185

[release/3.6] 新增内存显示条禁用样式

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/AdvancedVersionSettingPage.java
HMCL/src/main/resources/assets/lang/I18N.properties
HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

https://github.com/HMCL-dev/HMCL/pull/4192

[release/3.6] 修复 LWJGL 路径显示错误的问题

---

HMCL/src/main/resources/assets/lang/I18N_zh.properties
HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties

https://github.com/HMCL-dev/HMCL/pull/4376

[release/3.6] chore(l10n): change translation from 版本 to 实例 in zh-cn for term INSTANCE

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AccountAdvancedListItem.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/main/MainPage.java
HMCLCore/src/main/java/org/jackhuang/hmcl/util/Lang.java

现在这两个功能存在以下问题：
- 无法向上滚动
- 向下滚动时实际滚动方向错误

修复滚动切换游戏实例/账户功能

---

HMCL/src/main/java/org/jackhuang/hmcl/game/LauncherHelper.java
HMCLCore/src/main/java/org/jackhuang/hmcl/download/DefaultCacheRepository.java
HMCLCore/src/main/java/org/jackhuang/hmcl/download/game/GameLibrariesTask.java
HMCLCore/src/main/java/org/jackhuang/hmcl/download/game/GameRemoteLatestVersions.java
HMCLCore/src/main/java/org/jackhuang/hmcl/download/game/GameRemoteVersion.java
HMCLCore/src/main/java/org/jackhuang/hmcl/download/game/GameRemoteVersionInfo.java
HMCLCore/src/main/java/org/jackhuang/hmcl/download/game/GameRemoteVersions.java
HMCLCore/src/main/java/org/jackhuang/hmcl/download/game/GameVerificationFixTask.java
HMCLCore/src/main/java/org/jackhuang/hmcl/download/game/GameVersionList.java
HMCLCore/src/main/java/org/jackhuang/hmcl/download/game/LibraryDownloadTask.java

1. 将 `java.io.File` 迁移至 NIO；
2. 将部分类迁移至 record。

清理 org.jackhuang.hmcl.download.game

---

HMCL/src/main/java/org/jackhuang/hmcl/java/JavaManager.java
HMCLCore/src/test/java/org/jackhuang/hmcl/util/platform/JavaRuntimeTest.java

https://github.com/HMCL-dev/HMCL/pull/4515

[release/3.6] 优化 Java 自动选择规则

---

HMCL/src/main/java/org/jackhuang/hmcl/ui/ToolbarListPageSkin.java
HMCL/src/main/java/org/jackhuang/hmcl/ui/download/VersionsPage.java

Close https://github.com/HMCL-dev/HMCL/issues/4554
另外打开wiki按钮也有这个问题，也一起修了

修复添加 Java 和打开 Wiki 在点击相应按钮后始终保持焦点状态

---

HMCL/src/main/resources/assets/terracotta.json

https://github.com/burningtnt/Terracotta/compare/v0.3.9-rc.10...v0.3.10

Bump Terracotta to 0.3.10

---

HMCL/src/main/java/org/jackhuang/hmcl/terracotta/provider/MacOSProvider.java

可在 https://github.com/HMCL-dev/HMCL/discussions/4618 报告兼容性问题

修复 Terracotta 和部分 MacOS 版本的兼容性
