HMCL-dev/HMCL

HMCL/src/main/java/org/jackhuang/hellominecraft/launcher/views/MainPagePanel.form, HMCL/src/main/java/org/jackhuang/hellominecraft/launcher/views/MainPagePanel.java
Just because I cannot bear the previous alignment. :3
Before:
Profile|
|Version|
|Login
|Name
After:
|Profile
|Version
|Login
|Name
p.s. I don't have Swing Plugin, so I edit `MainPagePanel.form` myself. Also, I haven't tested Chinese version yet, but it should work fine.
=> Change alignment of profile and version to LEADING

HMCSM/src/main/java/org/jackhuang/hellominecraft/svrmgr/util/MonitorServiceImpl.java
Before:
After:
`top` for osx does not support the `-b` and `-n` option, but we can use `-l` instead
=> Fix cpu ratio for mac

HMCL/src/main/java/org/jackhuang/hellominecraft/launcher/core/launch/GameLauncher.java
这样可以避免一些文件如 logs 生成在脚本所在目录，而不是 .minecraft 目录
=> 在 Windows 的启动脚本里增加一行 cd %appdata%

HMCL/src/core/java/org/jackhuang/hellominecraft/launcher/core/launch/GameLauncher.java
修复跨分区的情况下一些文件如 logs 仍然生成在脚本所在目录，而不是 .minecraft 目录
/D 的作用可以在 cmd 内输入 cd /? 来查看
D 必须为大写
=> Windows 启动脚本中允许跨分区 cd

HMCL/src/main/java/org/jackhuang/hmcl/util/HMCLMinecraftLoader.java
Forge 1.12.x does not like the log4j.xml provided by HMCL.
=> partial rv 7fe3e28a, fixes Forge on 1.12

HMCLCore/src/main/java/org/jackhuang/hmcl/util/net/NetUtils.java
OptiFine is blocking access from User-Agents beginning with "Java/1."
=> Set a custom User-Agent, fixes optifine.net downloads

HMCLCore/src/main/kotlin/org/jackhuang/hmcl/download/MojangDownloadProvider.kt
Fixed invalid forge download url
[10:46:20] [org.jackhuang.hmcl.task.FileDownloadTask.execute/WARNING] Unable to download file http://ftb.cursecdn.com/FTB2/maven/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-installer.jar
java.io.IOException: Server error, response code: 404
at org.jackhuang.hmcl.task.FileDownloadTask.execute(FileDownloadTask.kt:88)
at org.jackhuang.hmcl.task.TaskExecutor.executeTask(TaskExecutor.kt:117)
at org.jackhuang.hmcl.task.TaskExecutor.access$executeTask(TaskExecutor.kt:30)
at org.jackhuang.hmcl.task.TaskExecutor$Invoker.call(TaskExecutor.kt:158)
at org.jackhuang.hmcl.task.TaskExecutor$Invoker.call(TaskExecutor.kt:154)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at …
=> Fixed invalid forge download url

HMCL/src/main/java/org/jackhuang/hmcl/Main.java, HMCL/src/main/java/org/jackhuang/hmcl/util/CrashReporter.java, HMCL/src/main/resources/assets/lang/I18N.properties, HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties
* 移除若是 OpenJDK 则不上传错误报告这一判定
* HMCL 3 使用 JavaFX，不会再遇到 Swing 问题了
* 当 JavaFX 缺失时，弹窗提示
* 考虑到 Java 11 及之前某些版本的 OpenJDK 不包含 OpenJFX（#179）
=> 对 OpenJDK 更好的支持

HMCL/src/main/java/org/jackhuang/hmcl/Launcher.java, HMCL/src/main/java/org/jackhuang/hmcl/upgrade/AppDataUpgrader.java, HMCL/src/main/java/org/jackhuang/hmcl/upgrade/UpdateChecker.java
通过 `-Dhmcl.version.override=xxx` 指定 HMCL 版本。
=> 添加 hmcl.version.override 选项用于调试更新功能

HMCL/src/main/java/org/jackhuang/hmcl/game/LauncherHelper.java, HMCLCore/src/main/java/org/jackhuang/hmcl/auth/Account.java, HMCLCore/src/main/java/org/jackhuang/hmcl/auth/CredentialExpiredException.java, HMCLCore/src/main/java/org/jackhuang/hmcl/auth/ServerResponseMalformedException.java, HMCLCore/src/main/java/org/jackhuang/hmcl/auth/yggdrasil/YggdrasilAccount.java, HMCLCore/src/main/java/org/jackhuang/hmcl/auth/yggdrasil/YggdrasilService.java
* 使用 `CredentialExpiredException` 而不是非 `ServerDisconnectException` 异常来指示需要进行密码登录
* 在一些非凭证过期的情况下，也会抛出非 `ServerDisconnectException` 异常，如 authlib-injector 下载失败、服务器响应畸形
* 仅当选择角色成功时，才将登录信息写入 `YggdrasilAccount` 的 `session` 字段
* 防止登录成功，但选择角色失败，造成 `YggdrasilAccount.session` 处于未选中角色的中间状态，引起 NPE
* 仅当 validate 操作返回 `ForbiddenOperationException` 异常时才认为 token 过期，而不是所有远程异常
=> 修复有关 Yggdrasil 登录的一些 bug

HMCL/src/main/java/org/jackhuang/hmcl/game/LauncherHelper.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/AccountLoginPane.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/AddAccountPane.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/AddAuthlibInjectorServerDialog.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/AddAuthlibInjectorServerPane.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/AuthlibInjectorServersPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/Controllers.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/Decorator.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/DialogController.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/LeftPaneController.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/MainPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/TwoLineListItem.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/animation/TransitionHandler.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/DialogCloseEvent.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/InputDialogPane.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/MessageDialogPane.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/TaskExecutorDialogWizardDisplayer.java, HMCL/src/main/java/org/jackhuang/hmcl/upgrade/AppDataUpgrader.java, HMCL/src/main/java/org/jackhuang/hmcl/upgrade/NewFileUpgrader.java, HMCL/src/main/java/org/jackhuang/hmcl/util/CrashReporter.java, HMCL/src/main/resources/assets/fxml/account-add.fxml, HMCL/src/main/resources/assets/fxml/authlib-injector-server-add.fxml, HMCL/src/main/resources/assets/fxml/authlib-injector-servers.fxml
* `TransitionHandler` 对整个 `view` 设置 `mouseTransparent`
* 避免 `TransitionHandler` 共用一个 `NULL` `StackPane`（防止一个节点多个父亲的情况）
* 从 `AuthlibInjectorServersPage` 分离出 `AddAuthlibInjectorServerPane`
* 移除错误信息中开头的 `class `（原来用的是 `.getClass()`，而不是 `.getClass().getName()`）
* 使用 `DialogCloseEvent` 取代 `Controllers.closeDialog`
* 移除一些错误原因推断
* `Trampoline` 误报率过高
* `java.lang.OutOfMemoryError` 一般情况下是程序问题（内存泄露），而不是用户环境问题
=> UI 重构 & bug 修复

HMCL/src/main/java/org/jackhuang/hmcl/setting/Accounts.java, HMCL/src/main/java/org/jackhuang/hmcl/setting/Config.java, HMCL/src/main/java/org/jackhuang/hmcl/setting/ConfigHolder.java, HMCL/src/main/java/org/jackhuang/hmcl/setting/Settings.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/AddAccountPane.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/AddAuthlibInjectorServerPane.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/AuthlibInjectorServersPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/export/ExportWizardProvider.java, HMCL/src/main/resources/assets/fxml/account-add.fxml, HMCL/src/main/resources/assets/fxml/authlib-injector-server-add.fxml
* 配置序列化/反序列化移至 `Config` 类中
* `Settings` 中关于 `Config` 的读写移至 `ConfigHolder`，WIP
* 由于改动较大，先进行合并防止冲突
* `AddAccountPane` 进行重构
* 使用数据绑定替代监听器
* 使用 `Controllers.dialog` 来显示选择角色界面
* 修复即使按钮禁用也可以通过回车继续
* 在登录时禁用对话框
* `AddAuthlibInjectorServerPane` 支持回车下一步
=> Refactor(WIP) & Fixes

HMCL/src/main/java/org/jackhuang/hmcl/ui/AccountPage.java, HMCL/src/main/resources/assets/fxml/account.fxml
* 修复账户信息页某项字段太长时，面板上下宽度不一致的问题。
* 在字段名称和字段值之间，插入 15px 间隙
* 当鼠标放在服务器名称上时，tooltip 显示服务器 URL
* 删除手动设置大小的代码，让 JavaFX 自己布局
=> 完善账户信息页的显示

HMCL/src/main/java/org/jackhuang/hmcl/ui/Decorator.java
> 之前在 #413 里提供了显示原生窗口按钮作为临时解决方案，这里恢复为使用自定义窗口边框。
调试了下，找到了 Mac 下窗口不能移动的原因是 `primaryStage.isMaximized()` 在 Mac 下为 true，只要移除 `onMouseMoved` 和 `onMouseDragged` 方法中对它的判断 Mac 下就可以正常拖动窗口了。
调试时加了下面这段代码监控它的值变化：
```
primaryStage.maximizedProperty().addListener((observable, oldValue, newValue) -> {
System.out.println(oldValue + " -> " + newValue);
});
```
发现是在窗口显示（`primaryStage.show()`）的时候变为 true 的，修改这个属性的地方在 natvie code 里，所以不知道问题出在哪。尝试过在 Listener 里把值改回去，但这样会导致窗口抖动（似乎 native code 还会把它设置回 true。。），所以解决方法就是 Mac 下别使用这个属性。
=> Mac 下恢复使用自定义窗口边框按钮

HMCL/src/main/java/org/jackhuang/hmcl/setting/ConfigHolder.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/InvocationDispatcher.java
确保配置文件保存时按照线程建立顺序执行。
最新Release中，对游戏目录列表中项目进行多次增、删、清空操作后，配置文件`hmcl.json`会保存文件不完整，导致各种清空下的游戏目录配置丢失。
经过对保存过程进行日志记录发现：
1. 某（几）次`synchronized`语句结束后，后续线程未能按照新建线程顺序进行执行；
2. 删除`synchronized`语句后，会导致某些情况下，多个保存线程冲突导致保存得到的配置文件混乱。
因此将原保存方式变换为使用`ExecutorService`进行队列式线程执行，测试（仅提交时最新分支javafx）得到的效果较好。
Signed-off-by: Chang Feng <chang_196700@hotmail.com>
=> Ensure sequential execution of configuration writer threads

README.md
I was always downloading from GitHub releases and I was wondering why there is no new version for months and many bugs weren't fixed. 
I just realized that the latest version is at https://hmcl.huangyuhui.net/download
this will guide people to the up-to-date version of HMCL.
=> add up-to-date download link

HMCL/src/main/java/org/jackhuang/hmcl/setting/Accounts.java, HMCLCore/src/main/java/org/jackhuang/hmcl/auth/authlibinjector/AuthlibInjectorDownloader.java
The process of searching for authlib-injector.jar has been changed to:
1. use ~/.hmcl/authlib-injector.jar if present
2. use ./authlib-injector.jar if present
3. download if neither of above is present
Instead of checking for updates when logging in, we now do it at startup. We only check for updates if there is at least one authlib-injector server configured.
This changed is expected to imporve launching speed.
=> Redesign authlib-injector updater

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/yggdrasil/YggdrasilService.java, HMCLCore/src/main/java/org/jackhuang/hmcl/auth/yggdrasil/YggdrasilSession.java
Ely.by's Yggdrasil response does not include `user` field. This commit makes the `user` field optional.
=> fix: not compatible with ely.by

HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/JavaVersion.java
Java 16 中由于 [JEP 403](https://openjdk.java.net/jeps/403)，默认 `illegal-access` 策略由 `permit` 调整为 `deny`，更强地封装了模块。
对于原版 Minecraft，这是无害的，因为它并未使用反射进行破坏封装的访问。但这种强封装会让很多 mod 无法在 Java 16 上工作，当尝试运行时会抛出 `IllegalAccessError`：
默认添加 JVM 参数 `--illegal-access=permit` 可以避免这种迁移风险。
**风险**：`--illegal-access` 参数在未来某个时候可能会被移除，到那时应该为该默认参数添加版本上界。
=> fix: IllegalAccessError on Java 16

HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java
根据 [JEP 403](https://openjdk.java.net/jeps/403) 在今天早晨的更新，`--illegal-access` 将会在 Java 17 删除，所以将该选项适用版本限制在 Java 16 上。
保留自动添加该选项依然有促进迁移的作用，所以暂时不移除，希望尽早发布包含相关更改的 HMCL 新版本以推动 Java 版本的更新。
=> fix: `--illegal-access` will be removed in Java 17

HMCL/src/main/java/org/jackhuang/hmcl/Launcher.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/export/ModpackFileSelectionPage.java
* 修复运行在 Java 16 上，HMCL 本体在包含中文字符的路径中时，导出包含启动器的整合包报 `NoSuchFileException` 的问题。
* 修复导出整合包向导添加文件时，反选 CheckBoxTree 中的某个节点后，勾选它的子文件无法正常包含的问题。
=> 修复导出整合包的相关问题

HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AddAccountPane.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AddAuthlibInjectorServerPane.java
* The most recently added authlib-injector server will be at the top of the list.
* In Add Account dialog, after adding an authlib-injector server, it will be automatically selected.
=> feat: select authlib-injector server after added

.gitignore, HMCL/src/main/java/org/jackhuang/hmcl/util/SelfDependencyPatcher.java, HMCL/src/main/resources/assets/openjfx-dependencies.json, tools/generate-openjfx-dependencies.sh
* SHA-1 checksum of OpenJFX dependencies are stored in `assets/openjfx-dependencies.json`.
* `openjfx-dependencies.json` can be generated using script `tools/generate-openjfx-dependencies.sh`.
=> feat: speed up OpenJFX dependencies checking

HMCLCore/src/main/java/org/jackhuang/hmcl/mod/mcbbs/McbbsModpackManifest.java
修复由于拼写错误导致HMCL导出的MCBBS整合包规范的整合包无法被其他工具和启动器识别的问题
=> 修复在manifest中的因拼写问题造成的与文档不符的问题

HMCL/build.gradle, HMCL/src/main/java/org/jackhuang/hmcl/upgrade/HMCLDownloadTask.java, HMCL/src/main/java/org/jackhuang/hmcl/upgrade/RemoteVersion.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/game/LibraryDownloadTask.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/Pack200Utils.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/SystemUtils.java, README.md, build.gradle
通过从 JDK 13 中移植出 Pack200 至独立库，解决当前 HMCL 无法在 OpenJDK 14 或更高版本上编译的问题，同时允许在任意版本 JDK 上支持 Pack200 相关功能。
该 PR 随时处于可用状态，但我仍需进行进一步测试。有什么好的测试例子吗？
=> 替换对 JDK 内置 Pack200 的依赖，允许在 JDK14 及更高版本上构建项目

HMCLauncher/HMCL/java.cpp
新版本Java只存在于新注册表中，而旧Java版本不能自动补全JavaFX，但是AdoptOpenJDK等构建的Java8也不包含JavaFX
> 其实最好能做成环境变量强制指定Java但是我懒得写（小声bb
=> HMCLLauncher: Search new Java registry location first

HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/TaskListPane.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/forge/ForgeInstallTask.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/forge/ForgeNewInstallTask.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/forge/ForgeOldInstallTask.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/game/GameVersionList.java, HMCLCore/src/main/java/org/jackhuang/hmcl/game/Version.java, HMCLCore/src/main/java/org/jackhuang/hmcl/task/Task.java
[Forge's InstallerTools](https://github.com/MinecraftForge/InstallerTools/blob/3aa10e8621a39c28e1d37985887181856469aea2/src/main/java/net/minecraftforge/installertools/DownloadMojmaps.java#L38) downloads Mojang mappings from [launchermeta.mojang.com](https://launchermeta.mojang.com/mc/game/version_manifest.json), even if HMCL is configured to use a mirror site. This PR patches the DOWNLOAD_MOJMAPS task to use HMCL's download source.
=> Patch Forge InstallerTools DOWNLOAD_MOJMAPS task to use download mirror

.github/workflows/release.yml
当 push  `v*.*.***` 形式的 tag 时，使用 GitHub Action 自动生成一个对应的 Release，并从黄鱼的 CI 服务器中下载对应的 exe 和 jar 文件上传至 release 中。
该方案不需要黄鱼的 CI 服务器连接至 GitHub。
该方案下，创建一个 Release 的流程：
* 黄鱼使用原本的流程，在 CI 服务器上部署新开发版
* 在仓库中执行以下命令（以 `3.3.198` 版本为例）：
```
git tag v3.3.198
git push --tags
```
我已经创建了一个测试仓库，并用该仓库进行了测试，该流程运行良好。参见 https://github.com/Glavo/JustTestHMCL/releases/tag/v3.3.198
=> 使用 GitHub Action 创建 GitHub Release

.github/workflows/gradle.yml
使用 JDK 8 构建时，Gradle 还会再下载一个 JDK 11 用于构建 `JavaFXPatcher`。直接使用 JDK 11 可以略减少 GitHub Action 用时。
=> 更新 GitHub Action 文件中的 JDK 版本至 11

HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/OperatingSystem.java
Fix
```
Exception in thread "main" java.lang.ExceptionInInitializerError
at org.jackhuang.hmcl.Metadata.<clinit>(Metadata.java:45)
at org.jackhuang.hmcl.Main.main(Main.java:51)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.regex.Pattern.matcher(java.lang.CharSequence)" because "org.jackhuang.hmcl.util.platform.OperatingSystem.MEMINFO_PATTERN" is null
at org.jackhuang.hmcl.util.platform.OperatingSystem.getPhysicalMemoryStatus(OperatingSystem.java:142)
at org.jackhuang.hmcl.util.platform.OperatingSystem.<clinit>(OperatingSystem.java:109)
... 2 more
```
=> fix: `MEMINFO_PATTERN` is `null`

HMCLCore/src/main/java/org/jackhuang/hmcl/mod/multimc/MultiMCInstanceConfiguration.java
在读取 `instance.cfg` 文件时用的 `Properties#load(InputStream)`，该方法总是以 `ISO 8859-1` 编码读取文件，所以会造成读取的内容乱码。
=> 修复读取MultiMC格式整合包时，整合包信息编码错误的问题

HMCL/src/main/java/org/jackhuang/hmcl/ui/FXUtils.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/UpgradeDialog.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/download/LocalModpackPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/download/RemoteModpackPage.java, HMCL/src/main/java/org/jackhuang/hmcl/util/SelfDependencyPatcher.java, HMCL/src/main/resources/assets/lang/I18N.properties, HMCL/src/main/resources/assets/lang/I18N_zh.properties, HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties
目前 HMCL 在展示整合包描述与更新日志时使用 `WebView`，因此强依赖  `javafx.web` 模块。
`javafx.web` 模块存在体积过大以及部分平台（譬如 `linux-arm32` 上）没有完整支持的问题。
OpenJFX 不提供 `javafx.web` 模块 `linux-arm32-monocle` 的分发，同时 LibericaJDK ARM32 Full JDK 虽然携带了 `javafx.web` ，但是在我树莓派4b 的 Ubuntu ARM32 平台上使用时会抛出 `UnsatisfiedLinkError`。
<details>
<summary>错误日志</summary>
[11:43:52] [org.jackhuang.hmcl.task.AsyncTaskExecutor.lambda$executeNormalTask$17/FINE] Executing task: org.jackhuang.hmcl.ui.download.LocalModpackPage.<init>(LocalModpackPage.java:125)
[11:43:52] [org.jackhuang.hmcl.task.AsyncTaskExecutor.lambda$executeNormalTask$17/FINE] Executing task: org.jackhuang.hmcl.ui.download.LocalModpackPage.<init>(LocalModpackPage.java:124)
[11:43:52] [org.jackhuang.hmcl.task.AsyncTaskExecutor.lambda$executeNormalTask$17/FINE] Executing task: …
=> 在缺失 javafx.web 的环境使用替代方案

HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/MultiFileItem.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/StringUtils.java
将过长的字符串缩短显示，使用 Tooltip 展示完整路径。
=> fix #1054: 避免长路径破坏 UI 布局

HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/JavaVersion.java
* AdoptOpenJDK 已经迁移，现在分别由 Eclipse 和 IBM 提供 HotSpot 与 J9 的版本：
* Eclipse Temurin 默认安装在 `%ProgramFiles%\Eclipse Foundation` 中
* IBM Semeru 默认安装在  `%ProgramFiles%\Semeru` 中
* 支持搜索 Minecraft 官方启动器所安装的 Java 8 以及 Java 16
=> 搜索更多 Java 安装

HMCL/src/main/java/org/jackhuang/hmcl/setting/ConfigHolder.java
In the case, the jar is at read only place but working directory is ok  
like the jar is installed to /usr/local/share/HMCL  
Although, It can be solved by touch the hmcl.json before start jar,  
I think fallback to working directory in code is better.
=> Check writable on jarfile for conifg init

HMCL/src/main/java/org/jackhuang/hmcl/Metadata.java
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables
> $XDG_CACHE_HOME defines the base directory relative to which user-specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.
=> Support XDG_Base_Directory environment variable

HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java
Windows 平台上，上下文中的 `classpath` 环境变量会覆盖这里设置的 `CLASSPATH` 环境变量，导致启动失败。手动设置 `classpath` 可以解决这个问题。
（PS：实际上 JVM 只识别全大写的 `CLASSPATH`，所以大写的 `CLASSPATH` 依然需要设置，否则 Linux/Mac OS 上无法启动）
=> Fix #1153: On Windows, the 'classpath' environment variable in the context overrides the 'CLASSPATH'

HMCLCore/src/main/java/org/jackhuang/hmcl/util/Logging.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/StringUtils.java
* 简化写法，让代码更明晰。
* `String.format` 每次都需要创建新的 `Formatter` 对象并解析格式字符串，`MessageFormat` 能省下这部分开销。
我用随机数据简单构建了一个 JMH 基准测试，测试中新的写法性能提高了 13%。理论上来说，内存占用也会略微降低。
```
Benchmark           Mode  Cnt       Score       Error  Units
FormatTest.testNew  avgt   15  779298.327 ± 54418.431  ns/op
FormatTest.testOld  avgt   15  896317.988 ± 31569.280  ns/op
```
* 仅在必要的时候创建 `ByteArrayOutputStream`。
* 调整部分缓冲的默认容量以减少内存分配。
=> 略微优化日志记录性能

HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java
Log4j2 被爆出严重的 RCE 漏洞，至目前为止所有版本都存在该漏洞。对于 Minecraft 服务器来说，任何成员只需要向服务器发送带有特定内容的字符串，即可控制服务器执行攻击者想要的命令。（修复见 apache/logging-log4j2#608）
由于 Minecraft 客户端允许在网络上共享世界，充当服务器的角色，此时也可能遭受类似的攻击。
该攻击是基于 Log4j2 中的 Message Pattern Lookup 功能，Minecraft 中似乎没有使用该功能，默认禁用它可以避免玩家在使用客户端开服时遭受对应攻击。
=> 默认情况下禁止 Minecraft 日志记录中使用 Message Pattern Lookup

HMCLCore/src/main/java/org/jackhuang/hmcl/download/optifine/OptiFineInstallTask.java
OptiFine 1.17.1 H1 开始，`net.optifine.Config` 移动至文件夹 `notch/net/optifine` 内。
=> 支持离线安装 OptiFine 1.17.1 H1 之后的版本

HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/CommandBuilder.java, HMCLCore/src/main/resources/assets/game/log4j2-1.12.xml, HMCLCore/src/main/resources/assets/game/log4j2-1.7.xml
为了安全起见，HMCL 现在默认禁用 Message Lookup，但这会破坏部分版本 Forge 以及某些 mod 的日志输出。
#1228 之后安全性已经被再次加强，所以可以略微放开对 Message Lookup 的限制：
* 默认情况下，依然禁用 Message Lookup；
* 当用户显式添加了 `-Dlog4j2.formatMsgNoLookups=false` JVM 参数时，启用 Message Lookup；
* JNDI Lookup 始终被禁用。
=> 允许用户通过 JVM 参数显式启用 Message Lookup

HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/CommandBuilder.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/JavaVersion.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/OperatingSystem.java, README.md
Java 17 以及更早版本中，`file.encoding` 会影响 Minecraft 的控制台编码，HMCL 应该识别该选项。
=> Fix #1148: 判断 Minecraft 控制台输出编码

HMCL/src/main/java/org/jackhuang/hmcl/ui/GameCrashWindow.java
=> fix: Bootstrap launcher version does not need to be displayed on GameCrashWindow

HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties
通过缩短I18N_zh_CN.properties中的字段解决多人联机界面过大的问题
效果图：
未经过修改：
=> 修复多人联机界面过大的问题

HMCL/src/main/java/org/jackhuang/hmcl/game/LogExporter.java
参见 #1297，导出崩溃信息时 `Schedulers.io()` 已经关闭，不应该使用它调度导出任务。
=> 修复导出崩溃信息失败

HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/OperatingSystem.java
根据 [JEP 421](https://openjdk.java.net/jeps/421)，`finalize` 方法即将被最终弃用，`System.runFinalization` 也将会被删除。
在 Java 18 中，`System.runFinalization` 已经带有 `@Deprecated(since="18", forRemoval=true)` 注解：
https://github.com/openjdk/jdk/blob/ec7cb6d5d305003429b51384ed72973767c70124/src/java.base/share/classes/java/lang/System.java#L1935
因此，应该做出一些预防措施避免 HMCL 在退出时因调用不存在方法发生崩溃。
=> 预防 HMCL 退出时崩溃

HMCL/src/main/java/org/jackhuang/hmcl/game/HMCLGameRepository.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/OperatingSystem.java
* 推荐内存最大不应该超过 8GB
* 对于自动内存分配
* 额外预留 256 MB 空间给堆外内存与 HMCL 自身；
* 空闲内存低于 8GB 时分配 80%，而超过 8G 的部分分配 20%；
* 自动内存分配不应该超过 32736MB，否则会导致压缩指针被禁用，更容易造成 OOM。
=> 调整默认内存分配策略

HMCL/build.gradle.kts
`application` 插件的 `run` task 并不很适合 HMCL，因为 HMCL 通常假设自己是一个 shadowJar。使用自定义的 `run` task 可以解决这个问题。
=> fix the 'run' task of Gradle

HMCLCore/src/main/java/org/jackhuang/hmcl/download/java/JavaDownloadTask.java
符号链接已存在时，`createSymbolicLink` 会抛出 `FileAlreadyExistsException`。
=> 修复下载 Java 时产生的崩溃

HMCLCore/src/main/java/org/jackhuang/hmcl/util/io/CompressingUtils.java
读取不存在的文件时 `readTextZipEntry` 会抛 NPE 而不是 IOE，导致 `readTextZipEntryQuietly` 直接抛异常了，而不是返回 `Optional.empty()`。
=> fix import curse forge modpack without modlist.html

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/DatapackListPageSkin.java
应该是 b2594122a89cb5a6a952c016d73bf85e511d5f90 中引入的问题，更改了调用的构造器导致在 `setPrefWidth(0)` 就已经绑定了值。
=> fix #1385: crash when show DatapackListPage

HMCL/src/main/java/org/jackhuang/hmcl/setting/Theme.java
目前 HMCL 不会清理创建的临时 css 文件，会让无用 css 在临时文件夹内大量堆积，所以应该在退出时删除它们。
=> 退出 HMCL 时删除 css 文件

HMCL/src/main/java/org/jackhuang/hmcl/game/LauncherHelper.java, HMCL/src/main/java/org/jackhuang/hmcl/game/LogExporter.java, HMCLCore/src/main/java/org/jackhuang/hmcl/auth/microsoft/MicrosoftSession.java, HMCLCore/src/main/java/org/jackhuang/hmcl/auth/yggdrasil/YggdrasilSession.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/Logging.java
* #1413：导出的启动脚本中包含敏感信息
* 虽然 `HMCLProcessListener` 过滤了 TOKEN，但 `ProcessExitedAbnormallyEvent` 中记录中依然包含敏感信息。
=> 加强对 TOKEN 的保护

javafx.gradle.kts
OpenJFX should be included in `testImplementation` dependencies, otherwise tests won't run on Java 11+.
=> Add openjfx to testImplementation dependencies

HMCL/src/main/java/org/jackhuang/hmcl/setting/Config.java
Currently non-Windows systems get a proportional font for logging. Bad.
Fix #139.
=> fix(config): Use Consolas by default on Windows only

HMCL/src/main/java/org/jackhuang/hmcl/game/LauncherHelper.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/DefaultDependencyManager.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/DependencyManager.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/game/GameLibrariesTask.java, HMCLCore/src/main/java/org/jackhuang/hmcl/task/FetchTask.java
`checkPatchCompletionAsync` 似乎以前从未工作过，因为它设计上目前只能修复 OptiFine 缺失，但又因为 `LibraryAnalyzer` 找不到 OptiFine 的库文件，所以它也修不了 OptiFine 的缺失问题。
另外原先的修复顺序很迷，我不明白为什么原先 `checkPatchCompletionAsync` 要在 `checkGameCompletionAsync` 之前执行。`checkGameCompletionAsync` 才检查的 version jar 的完整性，而 `checkPatchCompletionAsync` 的补全是需要 version jar 完整才能进行，没有导致崩溃似乎完全因为 `checkPatchCompletionAsync` 根本就没生效过……
=> 自动补全缺失的 OptiFine 文件

HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java
问题来自 TT 的报告：
#1141 的重复。将 #1145 的 workaround 扩展到 Mac OS 上以解决。
=> 修复 Mac OS 上不支持中文 Minecraft 路径的问题

HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/AdvancedListBox.java
fix #1258, fix #1397, fix #1559, fix #1589, fix #1646
将 AdvancedListBox 回滚至 9bef8b432b9095bdb470f7a1e7c1ce8fcab37c01，具体请见 #1646。
我不知道直接回滚会恢复哪些问题，但这个修改造成了数个极其严重的 UI 问题，如果黄鱼不接受这个 PR，也请快点解决。
希望解决后发个新版本，这些 UI 问题太恶心人了。
=> Revert AdvancedListBox

.github/workflows/gradle.yml
希望黄鱼能在 https://github.com/huanghongxun/HMCL/settings/secrets/actions 中添加下面三个 secrets：`MICROSOFT_AUTH_ID`、`MICROSOFT_AUTH_SECRET` 以及 `CURSEFORGE_API_KEY` ，这样就能使主仓库中 GitHub Action 提供的 DEV 构建也支持微软登录（fork 和 PR 不会读取 secrets，不受影响）。
这样的话，即使没发布新的开发版，依然能从 GitHub Action 中获取全功能的 HMCL，让更多用户及时获取更新内容。
=> 为快照版添加微软登录支持

HMCLCore/src/main/java/org/jackhuang/hmcl/launch/ExitWaiter.java
ExitWaiter 的更改导致某些异常退出无法被 HMCL 捕获，暂时回退了，捕获 OpenGL 版本报错的问题下次跟其他问题一起解决。
=> 修复 HMCL 无法捕获部分异常退出的问题

javafx.gradle.kts
通过提供自编译的 OpenJFX，支持在 LoongArch64 下自动下载 JavaFX。
=> 在 linux-loongarch64 平台自动下载 JavaFX

HMCL/src/main/java/org/jackhuang/hmcl/Launcher.java, HMCL/src/main/java/org/jackhuang/hmcl/setting/GlobalConfig.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/Controllers.java, HMCL/src/main/resources/assets/lang/I18N.properties, HMCL/src/main/resources/assets/lang/I18N_zh.properties, HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties, HMCL/src/main/resources/assets/natives.json, PLATFORM.md, javafx.gradle.kts
功能：
- 在 `windows-arm64` 平台自动补全本机库以实现一键启动；
- 支持在 `windows-arm64`  平台自动下载 JavaFX（官方未提供 WOA 平台 OpenJFX 构建，所以暂时使用我自行发布的版本）；
- 启动时提醒用户安装 OpenGL 兼容包，以避免高通 OpenGL 驱动版本过低的问题。
已知问题：
- 目前 Minecraft 1.6 与 1.7 能够启动，但窗口无法正常渲染；
- Minecraft 1.8~1.12.2 游戏过程中存在一些崩溃的问题；
- 部分版本与 Forge 兼容性不佳。
暂时没精力去解决这些问题，未来我可能会跟进。
=> 添加 Windows on Arm 平台的支持

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/OAuth.java
```diff
switch (response.error) {
case "invalid_grant":
>                 if (response.errorDescription.contains("AADSTS70000")) {
throw new CredentialExpiredException();
}
```
这样做的好处是一旦出现`invalid_grant`的`AADSTS70000`错误就直接重新登录
AADSTS70000就包括原来的那几个报错，还有我要加的报错
=> 修改 response.errorDescription.contains() 参数

HMCL/src/main/java/org/jackhuang/hmcl/ui/multiplayer/LocalServerBroadcaster.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/javafx/BindingMapping.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/OperatingSystem.java
OpenJFX 19 中为 `ObservableValue` 添加了 `map` 与 `flatMap` 方法，签名与 HMCL 的 `BindingMapping` 中同名同功能方法略有冲突，所以无法编译。本 PR 修复了此问题。
同时本 PR 也替换了一些新版本 JDK 中对弃用方法的调用。
=> fix build fails with Java 19

HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java
LWJGL2 加载本机库时内部使用 `String::getBytes()` 解码路径，所以依赖于默认编码，将 `file.encoding` 设置为 UTF-8 破坏了本机库加载，导致没有声音。
=> 修复中文路径下启动 <= 1.12.2 的版本没有声音的问题

HMCL/src/main/java/org/jackhuang/hmcl/ui/multiplayer/MultiplayerPage.java
不知道为啥 `clearSession();` 参数被注释掉了
https://user-images.githubusercontent.com/64117916/193602502-5a5b5317-9762-4262-ac93-8d858b8f18f3.mp4
=> 修复在多人联机出现报错时不会回到启动前状态

HMCL/src/main/java/org/jackhuang/hmcl/Metadata.java, HMCL/src/main/java/org/jackhuang/hmcl/setting/ConfigHolder.java
现在 Linux 上，HMCL 将 HMCL_DIRECTORY 放置在缓存目录中，但缓存目录仅应该存储非关键数据，随时可能被清理，而 HMCL_DIRECTORY 中已经存储了用户的关键数据，所以应该迁移到其他地方。
=> 在 Linux 上将 HMCL_DIRECTORY 迁移至用户目录中

HMCLCore/src/main/java/org/jackhuang/hmcl/task/FileDownloadTask.java
修复 `IntegrityCheck` 无法处理 SHA-256 的问题。
=> fix IntegrityCheck::performCheck

HMCL/src/main/java/org/jackhuang/hmcl/ui/FXUtils.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/MessageDialogPane.java, HMCL/src/main/resources/assets/fxml/message-dialog.fxml
似乎没有干净的做法来实现，我就用 hack 一点的方式来做了。
@huanghongxun 这个 PR 很重要，修复了非常影响使用体验的问题，希望合并本 PR 并重新编译 HMCLauncher.exe 后，立即发布新版本。
=> 修复 MessageDialogPane 总是折叠内容的问题

HMCL/build.gradle.kts
This allows compilation with `sourceCompatibility = 17`.
=> Bump Gradle Shadow to 7.1.2

HMCLCore/src/main/java/org/jackhuang/hmcl/util/io/JarUtils.java
JDK 8 上 `JarUtils.class.getResourceAsStream("/META-INF/MANIFEST.MF")` 似乎会在 classpath 里找到奇怪的 `MANIFEST.MF` 而不是 HMCL 的，所以改为用 `JarUtils.getManifest` 加载。
=> fix #1852: Lookup manifest in this jar

.github/workflows/check-style.yml, .github/workflows/check-translations.yml, .github/workflows/check-update.yml, .github/workflows/gradle.yml
`actions/setup-java@v2`、`actions/upload-artifact@v2` 和 `actions/checkout@v2` 已经被弃用，应更新至 v3。
=> Update GitHub Action

HMCL/src/main/java/org/jackhuang/hmcl/game/LauncherHelper.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/GameCrashWindow.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/LogWindow.java, HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java, HMCLCore/src/main/java/org/jackhuang/hmcl/launch/ProcessListener.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/Lang.java
HMCL 隐藏窗口后，作为后台进程，应该尽可能地降低性能与内存开销，以防干扰游戏表现。
目前 HMCL 监控游戏进程 stdout/stderr 的 `StreamPump` callback 开销尚不可忽略，可能轻微阻塞游戏进程的日志输出。
本 PR 通过细化锁粒度与惰性猜测日志级别，使其**开销降低约 1/2**，同时减少后台内存分配，降低开销。
=> Optimization HMCLProcessListener::onLog

HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java
由于 Log4j 将 `System.out` 作为字节流处理，绕过了 `System.out` 本身的编码而使用默认编码进行输出，导致 Java 18+ 上默认使用 UTF-8 进行日志，最后造成乱码。
将 `file.encoding` 默认设置为本机编码可以解决这一点。
=> 修复 Java 18+ Minecraft 日志乱码的问题

HMCL/src/main/java/org/jackhuang/hmcl/ui/FXUtils.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/main/DownloadSettingsPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/main/PersonalizationPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/VersionSettingsPage.java
* 在 `JFXTextField` 失去焦点时提交内容变化，避免在用户键入时不断地写入配置文件
* 校验 `JFXTextField` 的值，拒绝提交非法值并回滚
已测试以下场景以确保用户的修改总是能正确触发 `JFXTextField` 失去焦点事件：
=> 延迟提交 JFXTextField 的变化

HMCLCore/src/main/java/org/jackhuang/hmcl/download/java/JavaDownloadTask.java
* 修复文件已存在时无法通过校验的报错
* 使用镜像源下载 Java
* 跳过已经存在的文件
=> 修复 Java 下载相关问题

HMCL/src/main/java/org/jackhuang/hmcl/setting/Config.java, HMCL/src/main/java/org/jackhuang/hmcl/setting/Profiles.java
对普通的 ObservableMap 进行修改时，每修改一个值都会触发一次 invalid 事件，导致对每个 Profile 内容进行修改时，都会触发 `2 * Profile 总数` 次 invalid 事件（调用 `clear` 时为会为每个元素触发一次事件，调用 `putAll` 时又会触发一遍），反复进行保存。
将其更换为 `MapProperty` 后，每次 `set` 只会触发一次 invalid 事件。
=> Replace ObservableMap with MapProperty

HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/OperatingSystem.java
部分精简 JRE 中可能不包含 jdk.management 模块，应捕获异常防止启动时崩溃。
=> 允许 OperatingSystemMXBean 不存在

HMCL/src/main/java/org/jackhuang/hmcl/util/SelfDependencyPatcher.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/io/CompressingUtils.java
本 PR 修复后，HMCL 能够在仅包含 `java.se` 和 `jdk.unsupported` 的 JRE 上运行。当 `jdk.zipfs` 缺失时不会崩溃，但会影响正常启动。
=> 修复在精简 JRE 上崩溃的问题

HMCLCore/src/main/java/org/jackhuang/hmcl/game/World.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/io/Zipper.java
现在 `Zipper` 基于 ZipFileSystem 实现，当导出包含大量内容的压缩包时，会长时间卡住且创建上千甚至上万个临时文件，给用户带来困扰。特别是导出位置在桌面上的时候，会导致桌面被临时文件直接塞满，非常糟糕。
现在将其实现重写为 `ZipOutputStream`，不再创建临时文件，且性能得到大幅优化。
=> close #1199:  重新实现 Zipper

HMCL/src/main/java/org/jackhuang/hmcl/game/HMCLGameRepository.java
* 为 HMCL 本体保留更多内存
* 将自动内存分配最高限制降低至 16GiB
=> Optimize automatic memory allocation

HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/OperatingSystem.java
`~/.{folder} -> $XDG_DATA_HOME/{folder}`
~/.hmcl 里似乎没存什么重要内容，而且也不是配置文件，都是自动下载的 javafx / config.json ，这个文件的内容看起来不常更新，全都把他们放在 XDG_DATA_HOME 应该也没问题。
Disclaimer: XDG_DATA_HOME 不会周期性删除，因此不存在 #1785 提到的问题
Link: https://github.com/huanghongxun/HMCL/pull/1785
Link: https://github.com/huanghongxun/HMCL/issues/849
---
在 https://github.com/huanghongxun/HMCL/issues/849 中，提到了可以配置 HMCL Directory ，但实际上好像并无此选项？
=> feat: use XDG_DATA_HOME as for Linux working directories

HMCL/src/main/java/org/jackhuang/hmcl/Launcher.java, HMCL/src/main/java/org/jackhuang/hmcl/Metadata.java, HMCL/src/main/java/org/jackhuang/hmcl/setting/ConfigHolder.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/OperatingSystem.java, README.md, README_cn.md
* 修复被 #1948 造成的无法找到用户 Minecraft 文件夹的问题；
* 新添加 JVM 选项 `hmcl.home`，允许用户自行指定 HMCL_DIRECTORY 。
=> 更新查找 HMCL_DIRECTORY 文件夹的逻辑

HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/JavaVersion.java
理论上后面有一个 `toRealPath()`，不应该出问题的，不知道这个 issue 是啥情况。
`toAbsolutePath()` 能够补全 `:` 后的 `\`，不管是啥原因出的问题应该都能修复了吧。
=> fix #1905: fix path splicing

HMCL/src/main/java/org/jackhuang/hmcl/ui/main/AboutPage.java
不添加 logo 的话，排版太丑了
在弄明白图标版权问题前，先把 HMCL Logo 放那吧。
=> Add icon for qq channel

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/VersionSettingsPage.java
允许用户选择 `javaw.exe` 没有什么意义，反而因为有两个选择可能造成混乱。
=> Delete javaw.exe extension filter

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/offline/Texture.java
`ImageIO.read` 不会关闭接受的 `InputStream`，因此导致内存泄漏。
=> fix memory leak

HMCL/build.gradle.kts
本 PR 提议放弃通过 Pack200 压缩 HMCL。
理由：
* 由于新版 Minecraft 开始使用 Java 17，高版本 Java 的使用率提高，而 Java 14 中已经移除了 Pack200 支持，因此 Pack200 的使用率越来越低，意义逐渐减小；
* 现在 HMCL 服务器仅需要提供更新内容的 JSON 元数据，放弃支持 Pack200 能够让 JSON 元数据减少约 33% 的体积，降低 HMCL 服务器的负载；
* 不分发 `.pack` 文件后可以省略构建过程中的 `repack` 操作，提高构建效率；
* HMCL 的 `.pack.xz` 文件有时候会触发 Sonatype 的 BUG，导致新版本无法正常发布（Glavo/HMCL-Update/issues/2），阻塞新版本发布流程，此问题至今尚未完全解决。
这些问题中影响最大的是 Sonatype 上传的 BUG，一旦触发就会严重影响新版本发布进程，我不得不反复与 Sonatype 沟通，由 Sonatype 工作人员手动给我放宽限制才能正常发布新版本。
因此，我已经在 HMCL-Update 中放弃上传其他格式的分发，仅上传 `.jar` 文件，避免不必要的麻烦。
在 HMCL-Update 放弃 `.pack` 与 `.pack.xz` 后，HMCL 使用 Pack200 压缩的意义不再存在，所以我希望 HMCL 直接放弃使用 Pack200 压缩。
由于 HMCL 会检查更新 JSON 中是否包含 `packxz` 值，不存在时 HMCL 会自动选择下载 jar，所以不会造成问题。
`org.jackhuang.hmcl.upgrade` 中对 Pack200 的可选支持继续保留，如果以后因为某种原因需要重新加入 Pack200，HMCL 依然会自动尝试下载 `.pack.xz` …
=> 不再使用 Pack200 压缩构建

HMCL/src/main/java/org/jackhuang/hmcl/util/i18n/Locales.java
=> 使用 Locale.forLanguageTag 替代构造器调用

HMCL/src/main/java/org/jackhuang/hmcl/ui/LogWindow.java
这样日志崩溃窗口的导出日志里面的 minecraft.log 就可以有 10000 行
=> 将日志窗口的最大输出值调整至 10000

javafx.gradle.kts
避免在没有 JavaFX 的 JDK 上构建 HMCL 时将 JavaFX 打包进 HMCL 中。
=> 从 JAR 中排除 JavaFX

HMCL/src/main/java/org/jackhuang/hmcl/ui/main/DownloadSettingsPage.java
=> 修复下载源选择 ComboBox 过长的问题

HMCLCore/src/main/java/org/jackhuang/hmcl/event/EventBus.java
避免在每次 `fireEvent` 时创建新的 `EventManager`。
=> Use computeIfAbsent in EventBus

HMCL/src/main/java/org/jackhuang/hmcl/ui/SVG.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/AdvancedVersionSettingPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/VersionSettingsPage.java, HMCL/src/main/resources/assets/lang/I18N.properties, HMCL/src/main/resources/assets/lang/I18N_es.properties, HMCL/src/main/resources/assets/lang/I18N_ja.properties, HMCL/src/main/resources/assets/lang/I18N_ru.properties, HMCL/src/main/resources/assets/lang/I18N_zh.properties, HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties
目前版本设置页包含大量设置项，每次点开都需要初始化很多控件，配置较差的机器上会引发秒级的界面卡顿。
由于游戏管理和启动器设置的默认页面都是版本设置页，导致此卡顿的影响尤为明显。
本 PR 将高级设置分拆至单独页面中，仅在需要的时候初始化，从而缓解卡顿的问题。
=> 将版本高级设置拆分至单独页面中

HMCLCore/build.gradle.kts
=> Bump dependencies

HMCLCore/src/main/java/org/jackhuang/hmcl/util/versioning/VersionNumber.java, HMCLCore/src/test/java/org/jackhuang/hmcl/util/versioning/VersionNumberTest.java
JMH 测试结果表明，该 PR 使 `asVersion` 的性能提升了 50%~130%，纯数字的 `VersionNumber` 比较的性能提升了约 70%，`isIntVersion` 的性能提升了 70%~620%。
<details><summary>测试源码</summary>
```java
@Warmup(iterations = 5, time = 3)
@Measurement(iterations = 5, time = 3)
@Fork(value = 1, jvmArgsAppend = {"-XX:+UseG1GC", "-Xms8g", "-Xmx8g"})
@BenchmarkMode(Mode.Throughput)
@OutputTimeUnit(TimeUnit.MILLISECONDS)
@State(Scope.Benchmark)
public class VersionNumberBenchmark {
@Benchmark
public VersionNumber asVersion1() {
return VersionNumber.asVersion("1.8");
}
@Benchmark
public VersionNumber asVersion2() {
return VersionNumber.asVersion("1.7.10forge1614_FTBInfinity");
}
private static final VersionNumber v1 = VersionNumber.asVersion("1.16.3");
private static final VersionNumber v2 = VersionNumber.asVersion("1.16.5");
@Benchmark
public …
```
=> 优化 VersionNumber

HMCL/src/main/java/org/jackhuang/hmcl/Launcher.java, HMCL/src/main/resources/assets/lang/I18N.properties, HMCL/src/main/resources/assets/lang/I18N_zh.properties, HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties
macOS 使用了 [App Translocation](https://lapcatsoftware.com/articles/app-translocation.html) 机制，可能会自动将 HMCL 移动至 `/private/var/folders` 中的临时文件夹内，导致用户关闭 HMCL 后游戏数据和设置丢失。
=> 检测 macOS 上的 App Translocation

HMCL/src/main/java/org/jackhuang/hmcl/Main.java, HMCL/src/main/java/org/jackhuang/hmcl/util/FractureiserDetector.java, HMCL/src/main/resources/assets/lang/I18N.properties, HMCL/src/main/resources/assets/lang/I18N_zh.properties, HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties
HMCL 应当拒绝在被 Fractureiser 病毒感染的设备上启动。
=> 启动时检测 Fractureiser 病毒

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModListPageSkin.java
Changed to emphasize the name and version reported by mods, instead of the filename. Search behavior is unaffected.
Improves user interface in my own opinion.
=> Reorder emphasis priority of mod info elements in list entry

HMCLCore/src/main/java/org/jackhuang/hmcl/mod/curse/CurseAddon.java
使 CurseForge 源的 ModItem 能够渲染多个 ModLoader
同时与 Modrinth 源的代码保持一致
https://github.com/huanghongxun/HMCL/blob/126a6dbbed4df0f51aeb32dbfcbf6570d54b139b/HMCLCore/src/main/java/org/jackhuang/hmcl/mod/modrinth/ModrinthRemoteModRepository.java#L497C1-L502C52
=> 添加 Curse RemoteMod.Version 对多个 ModLoaderType 的支持

HMCL/src/main/java/org/jackhuang/hmcl/ui/download/DownloadPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ResourcePackDownloadListPage.java, HMCLCore/src/main/java/org/jackhuang/hmcl/mod/modrinth/ModrinthRemoteModRepository.java
=> Support #1775 Enable HMCL to download resource packs from Modrinth.

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModListPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModListPageSkin.java
Close #2365 
现在在 Mod 管理界面点击任何一个 Mod 右侧的 i 按钮，即可点击 Curseforge / Modrinth 按钮来根据对应远程 Mod 仓库的信息查看前置与可用版本
=> Support #2365 Support viewing mods in ModListPage

HMCL/src/main/java/org/jackhuang/hmcl/ui/account/CreateAccountPane.java
**#2309 在 `org.jackhuang.hmcl.ui.account.CreateAccountPane#onAccept` 中加入了判断离线账户用户名是否合法的逻辑，但有巨大问题！**
**当创建非离线账户或离线账户用户名合法时，不会运行创建账户的逻辑！**
@huanghongxun @Glavo 请尽快处理本 PR！****
Fix #2372
=> Urgent Fix #2372 创建账户时卡死

HMCL/src/main/java/org/jackhuang/hmcl/game/HMCLGameRepository.java
Close #2337 
目前的逻辑是：
优先考虑 Fabric，Forge，Quilt，如果有三者之一就使用他们的图标；
其次考虑 Optifine，若有则用 Optifine 图标；
其次考虑 LiteLoader，若有则用 LiteLoader 图标；
否则就草方块
**警告：该 PR 引入了新的对 PNG 素材的引用，可能与 #2276 冲突！**
=> Support #2337 selecting the best icon when a new version is installed.

.github/workflows/gitee.yml
Update `Hub Mirror Action` to 1.3 
[Release note](https://github.com/Yikun/hub-mirror-action/releases/tag/v1.3)
> 升级PyYaml以修复PyYaml安装问题 https://github.com/Yikun/hub-mirror-action/pull/182
> 开启pull_request_target帮助开发者触发CI验证 https://github.com/Yikun/hub-mirror-action/pull/139
> 新增clone_style的说明文档 https://github.com/Yikun/hub-mirror-action/pull/146 感谢@AdoShan
> 新增与repo-list-generator共同使用的文档 https://github.com/Yikun/hub-mirror-action/pull/150 感谢@yi-Xu-0100 
Fix sync to gitee action
`ModuleNotFoundError: No module named 'yaml'`
[show detail](https://github.com/huanghongxun/HMCL/actions/runs/5783970016/job/15673761600)
Signed-off-by: yangyangdaji <1504305527@qq.com>
=> (workflows/gitee.yml) Update `Hub Mirror Action` to 1.3

HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java
在Windows上也可以使用系统OpenAL和系统GLFW
只是有一些用户没有正确设置而已
=> System GLFW & System OpenAL are available on Windows too

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModListPage.java
修复启动器崩溃
```
---- Hello Minecraft! Crash Report ----
Version: 3.5.5
Time: 2023-09-12 19:48:13
Thread: Thread[#39,ForkJoinPool.commonPool-worker-2,5,main]
Content:
java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "result" is null
at org.jackhuang.hmcl.ui.versions.ModListPage.lambda$checkUpdates$12(ModListPage.java:193)
at org.jackhuang.hmcl.task.Task.lambda$whenComplete$7(Task.java:753)
at org.jackhuang.hmcl.task.Task$1.execute(Task.java:714)
at org.jackhuang.hmcl.task.AsyncTaskExecutor.lambda$executeNormalTask$22(AsyncTaskExecutor.java:245)
at org.jackhuang.hmcl.util.Lang.lambda$wrap$2(Lang.java:291)
at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
at javafx.graphics@19.0.2.1/com.sun.javafx.application.PlatformImpl …
```
=> Fix missing null checking.

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/authlibinjector/AuthlibInjectorDownloader.java, HMCLCore/src/main/java/org/jackhuang/hmcl/auth/authlibinjector/AuthlibInjectorServer.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/io/HttpRequest.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/io/IOUtils.java
通过 new URL(url).openStream() 做网络请求时，若代理设置出错，Java 内部会抛出 NPE
使用 HttpRequest.GET 调用已封装好的 new URL(url).openConnection() 即可避免此问题
=> Fix #2375 Fix network NPE

HMCLCore/src/main/java/org/jackhuang/hmcl/mod/RemoteMod.java, HMCLCore/src/main/java/org/jackhuang/hmcl/mod/curse/CurseAddon.java
The return value of the dependent mods may be duplicated from CurseForge API.
Fix #2629
=> Fix #2629 Duplicated dependent mods

HMCL/src/main/java/org/jackhuang/hmcl/ui/decorator/DecoratorSkin.java, HMCL/src/main/resources/assets/css/root.css
**@huanghongxun 目前在打开标题栏透明时，button 都会以白色渲染，但标题会以黑色渲染！样式不同一**
=> [Fix 1932] Render title in white at anytime

HMCLCore/src/main/java/org/jackhuang/hmcl/util/io/NetworkUtils.java
统一超时时间到 8000ms
旧版本 3000ms，目前遗留的 5000ms 均远小于浏览器的超时时间（60000ms），导致中国大陆地区的用户容易出现浏览器打得开，但 HMCL 打不开的情况
=> Set the network timeout to 8000ms.

HMCLCore/build.gradle.kts, HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/ManagedProcess.java
@burningtnt 
首先，不要拿哈希值充当版本号。哈希值无法给维护者带来有意义的信息，让维护者更难去追踪库版本的变更。除非这个库只有你自己一个人用，不然请用一个有意义的版本号，就算想偷懒那最少也请在哈希前面附加上时间戳。
然后不要想性能想的入魔了。
如果能够在清理简化代码的同时带来性能提升，那自然是好的；如果为了优化需要让代码更复杂，那除非确认能带来用户有感知的改进，不然请确保代码依然有很高的可读性，并且要权衡为此变化付出的代价是否值得。不是只有对运行时性能的影响是代价，审查和测试付出的精力也是代价，后续的维护成本也是代价。在提交一项更改前，请先把收益和代价想清楚再说。
对于性能优化来说，如果是一秒会调用成千上万次的方法，那么能优化掉几毫秒的开销是很值得的；如果是像日志处理这样每秒最多可能调用几十次的方法，优化掉几毫秒的开销依然有用，但算不上那么重要；如果是整个程序周期里就调用几次的方法，尤其是那些比较少用还涉及到 IO 等重开销的功能，哪怕每次调用一次多花一两百毫秒都不会对用户体验造成多少影响，为了优化它提高维护成本很可能是不划算的。
`ManagedProcess::getPid()` 这个方法属于很少使用的功能，用到的地方还涉及 I/O，所以对开销的容忍程度很高。在这里，用反射查询并调用一次 `pid` 的时间大概是几十到几百微秒，远不到一毫秒，除非塞进循环里高频调用，否则对用户来说完全没有任何可感的区别。为了优化掉这微秒级别的开销，你在这里付出的代价是：
* 每个阅读 `ManagedProcess` 以及构建脚本源码的开发者都要额外去理解和学习这些非常规的代码的含义；
* 重构代码可能会破坏构建，需要花额外的精力额外维护构建脚本；如果构建前没有 clean，甚至还可能会在不破坏构建的情况下损坏功能；
* 对字节码进行修改可能会造成隐蔽的 BUG（尤其是与 …
=> 清理 ManagedProcess::getPid()

HMCL/src/main/java/org/jackhuang/hmcl/ui/download/AdditionalInstallersPage.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/LibraryAnalyzer.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/neoforge/NeoForgeInstallTask.java, HMCLCore/src/main/java/org/jackhuang/hmcl/mod/mcbbs/McbbsModpackExportTask.java, HMCLCore/src/main/java/org/jackhuang/hmcl/mod/multimc/MultiMCModpackExportTask.java, HMCLCore/src/main/java/org/jackhuang/hmcl/mod/multimc/MultiMCModpackInstallTask.java, HMCLCore/src/main/java/org/jackhuang/hmcl/mod/server/ServerModpackExportTask.java
NeoForge 近期把 installer_profile.json 里的 $.profile 改成 "NeoForge" 了……
Fix #2637 Fix #2649
#2654 处理了一部分（MultiMC 的 NeoForge 支持依然在 Draft 阶段 https://github.com/MultiMC/Launcher/pull/5323 ）合并后需根据其 UID 配置 HMCL 内的代码
=> Fix: NeoForge Support

HMCL/src/main/java/org/jackhuang/hmcl/setting/DownloadProviders.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/BalancedDownloadProvider.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/MultipleSourceVersionList.java
现在 HMCL 在开启自动选择下载源（平衡）模式的情况下，每次读取版本列表时都会同时尝试从官方源、mcbbs 源和 BMCL 源获取，并在其中之一失败时失败。现在由于 mcbbs 源离线，开启自动选择下载源时已经完全无法正确获取版本列表。
本 PR 修复了获取版本列表的逻辑，按照 官方源 -> mcbbs 源 -> BMCL 源 的顺序依次获取，当且仅当从前一个源获取失败时才会尝试下一个源，这样能够保证只要能正常访问任何一个源都能得到结果，也避免对 BMCL 产生不必要的压力。
=> Fix #2690: 修复自动选择下载源功能

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/authlibinjector/AuthlibInjectorDownloader.java
目前 HMCL 只会从首选下载源获取 `AuthlibInjectorVersionInfo`，这会导致开启自动选择下载源时只要访问 mcbbs 源失败就会直接失败，而不会尝试从官方源获取。
=> 尝试从候选源获取 AuthlibInjectorVersionInfo

HMCLCore/src/main/java/org/jackhuang/hmcl/download/neoforge/NeoForgeBMCLVersionList.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/neoforge/NeoForgeOfficialVersionList.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/neoforge/NeoForgeRemoteVersion.java, HMCLCore/src/main/java/org/jackhuang/hmcl/mod/multimc/MultiMCModpackExportTask.java, HMCLCore/src/main/java/org/jackhuang/hmcl/mod/multimc/MultiMCModpackInstallTask.java
1.20.1 的 NeoForge 版本号有好几种变化
在 HMCL 内部，均选取 47.1.* 和 NeoForge 版本号规范中敲定的形式
因此，在读取数据源时，需要做出转化
本 PR 补上了安装整合包时没有对各类版本号做出转化的 Bug
转化分为两步，先转换为 HMCL 内部 NeoForge 版本号
- 1.20.1-forge-47.1.58 -> 47.1.58
- 1.20.1-47.1.58 -> 47.1.58
再转换为 BMCL / NeoForge Maven 所支持的版本号
BMCL:
- 47.1.58 -> 1.20.1-47.1.58
- 47.1.81 -> 1.20.1-forge-47.1.81
NeoForge Maven:
- 47.1.84 -> 1.20.1-47.1.84
- 47.1.82 -> 47.1.82（特例，鬼知道为什么就这一个版本号这么特殊）
=> Fix: Cannot install modpacks with NeoForge for Minecraft 1.20.1.

HMCL/src/main/java/org/jackhuang/hmcl/ui/InstallerItem.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/download/InstallersPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/InstallerListPage.java
本 PR 为 Minecraft 1.13+ 隐藏 liteloader 的安装选项，为 1.12.2 以及更早版本隐藏 NeoForge、Fabric 以及 Quilt 的安装选项，以避免安装界面不得不出现滚动条。
=> 在游戏安装界面隐藏不可用的模组管理器

HMCL/src/main/java/org/jackhuang/hmcl/ui/InstallerItem.java
目前检测 `InstallerItem` 是否兼容的代码过于冗长，难以阅读且难以维护，很容易出现问题（比如目前就会在选中 NeoForge 后禁止安装 OptiFine，却不会在选中 OptiFine 后禁止安装 NeoForge），本 PR 改进了相关代码以提升可读性和可维护性。
=> 改进 ModLoader 兼容性检测

.github/workflows/build-launcher.yml, .github/workflows/check-style.yml, .github/workflows/check-translations.yml, .github/workflows/check-update.yml, .github/workflows/gradle.yml
通过更新 `actions/checkout`、`actions/setup-java` 以及 `actions/upload-artifact` 至 v4 避免 Node.js 16 的弃用警告。
=> 更新 GitHub Action 脚本

HMCL/src/main/java/org/jackhuang/hmcl/setting/Theme.java
本 PR 使 HMCL 在未设置字体时会尝试从当前路径寻找 `font.ttf` 或 `font.otf` 并加载为默认字体。
这项功能的目的是：
* 使整合包作者能够更方便地定制 HMCL 界面字体
* 给界面乱码问题提供一个简单易操作的解决方案
=> 支持从当前路径加载字体

HMCL/src/main/java/org/jackhuang/hmcl/ui/main/AboutPage.java
=> 更新指向 XZ 主页的链接

HMCLCore/src/main/java/org/jackhuang/hmcl/mod/modinfo/ForgeNewModMetadata.java
=> Support #3000: Support neoforge.mods.toml 

HMCLCore/src/main/java/org/jackhuang/hmcl/util/logging/Logger.java
loggerThread.join()陷入死循环，因此设置等待时长来解决这个问题
100ms理论上足够计算机处理大部分日志指令了
=> Fix #3071: 在 HMCL 被终结时停止日志线程

HMCL/src/main/java/org/jackhuang/hmcl/ui/InstallerItem.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/InstallerListPage.java, HMCL/src/main/resources/assets/lang/I18N.properties, HMCL/src/main/resources/assets/lang/I18N_zh.properties, HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties, HMCLCore/src/main/java/org/jackhuang/hmcl/download/LibraryAnalyzer.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/MaintainTask.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/forge/ForgeInstallTask.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/game/GameLibrariesTask.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/optifine/OptiFineInstallTask.java, HMCLCore/src/main/java/org/jackhuang/hmcl/game/Version.java
=> 修复自动安装在 1.20.4 的严重问题

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/VersionSettingsPage.java
=> Fix #3006: 全局游戏设置中版本隔离开启后的显示的路径的版本号为”null“

HMCLCore/src/main/java/org/jackhuang/hmcl/mod/curse/CurseForgeRemoteModRepository.java
432 is gameid for minecraft
https://docs.curseforge.com/#get-fingerprints-matches-by-game-id
https://github.com/Hex-Dragon/PCL2/blob/d682b598032bc4c7e3b1367cae4d51d037007ae9/Plain%20Craft%20Launcher%202/Modules/Minecraft/ModMod.vb#L1029-L1030
=> Add 432 gameid for curseforge fingerprints matching

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/microsoft/MicrosoftSession.java
Fix #3080
Gson 默认将该值反序列化为 Double
=> 修复 #3080 微软账户无法正确读取 Token 过期时间的问题

HMCLCore/src/main/java/org/jackhuang/hmcl/download/MojangDownloadProvider.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/forge/ForgeVersionList.java
使用了 https://github.com/zkitefly/forge-maven-metadata 的 https://zkitefly.github.io/forge-maven-metadata/list.json
该 json 格式根据 [https://bmclapi.bangbang93.com/maven/net/minecraftforge/forge/json](https://bmclapi.bangbang93.com/maven/net/minecraftforge/forge/json) 和代码必要参数
https://github.com/user-attachments/assets/e2f0d0d2-9ef1-4be8-b3ad-bea48ee68613
**由于目前 BMCLAPI 队国外 IP 进行封禁，需要增加 Forge 官方源减少国外玩家所受到的影响**
顺便合并一下 https://github.com/HMCL-dev/HMCL/pull/2719 吧
=> 支持 Forge 官方源

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/VersionPage.java
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
A minor QOL change. Logically, instance settings and loader versions are the first things that an experienced Minecraft player would adjust. Also, the manage mods page is useless if no loaders are installed, so the loaders page should be prioritized higher.
=> Adjust the order of sidebars in instance settings

HMCL/build.gradle.kts, HMCL/src/main/resources/assets/openjfx-dependencies.json, javafx.gradle.kts
我观察到每次新开一个分支并构建时，生成 `openjfx-dependencies.json` 总是花费不少时间。考虑到此文件修改不频繁，预生成它能够优化构建时的体验，也便于查看文件历史。
=> 预生成 openjfx-dependencies.json

HMCL/src/main/java/org/jackhuang/hmcl/ui/main/DownloadSettingsPage.java
Only it is aligned to the right… looks weird, does not it? This PR fixes that.
<details>
<summary>Wrong align</summary>
</details>
=> Fix alignment of host and port in proxy settings

HMCL/src/main/java/org/jackhuang/hmcl/ui/main/DownloadSettingsPage.java
<details>
<summary>Before</summary>
</details>
The titles of these two settings are obviously inappropriate - this PR changes them to the appropriate i18n key.
=> Download source and thread setting titles i18n key

HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AccountListPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/download/DownloadPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/main/LauncherSettingsPage.java
Only the main page’s relevant text is capitalized, and other pages are not — this PR will force capitalization in the remaining few places.
It is important to note that this issue can only be noticed in non-Chinese languages.
*Previous introductions: #3255*
=> Capitalize text above the sidebar line

.github/workflows/gradle.yml, HMCLCore/build.gradle.kts, HMCLCore/src/main/java/org/jackhuang/hmcl/game/CrashReportAnalyzer.java, HMCLCore/src/test/java/org/jackhuang/hmcl/game/CrashReportAnalyzerTest.java
目前 HMCL 需要与 Java 8 兼容，并且黄鱼的 CI 服务器上仍在使用 Java 8 构建开发版和正式版的 HMCL。
本 PR 将 GitHub Action 调整为使用 Java 8 构建项目，这样能及时检测出代码中是否误用了高版本 Java/JavaFX 的 API，避免发布新版本时才构建失败。
此外本 PR 修复了一个会导致 Java 8 卡死的正则。
=> GitHub Action 使用 Java 8 构建 HMCL

HMCLCore/src/main/java/org/jackhuang/hmcl/download/java/disco/DiscoFetchJavaListTask.java, HMCLCore/src/main/java/org/jackhuang/hmcl/download/java/disco/DiscoJavaDistribution.java
* 修复 Java 下载窗口会在 GraalVM 尚未支持的平台展示 GraalVM 选项的问题
* 修复部分平台下载 Liberica JDK 会选择 lite jdk 的问题
=> 优化 Java 下载功能

HMCLCore/build.gradle.kts
commons-compress 1.26.0 引入了 commons-codec、commons-io 和 commons-lang3 作为依赖项，使 HMCL 体积明显增加，但并没有明显的收益，所以暂时还原至 1.25.0。未来我可能考虑维护 commons-compress 的[一个更干净的 fork](https://github.com/Glavo/kala-compress)。
=> Revert "Bump commons-compress to 1.27.1"

HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties
Content of `game.crash.reason`
Removed `game.crash.reason.failed_to_load_a_library` and `game.crash.reason.fabric_reports_an_error_and_gives_a_solution` as they were not used.
`- 在全局（特定）游戏设置，高级设置中打开“使用 OpenGL 软渲染器”（开启此选项后帧数会显著降低，仅推荐在以调试为目的或应急时开启）。`
This is inconsistent with the actual situation, so it is removed.
*The diff view on GitHub looks weird, and I am not sure why.*
Others:
- #3343
- #3348
- #3349
=> Revise zh_CN part 2

HMCL/src/main/java/org/jackhuang/hmcl/ui/account/CreateAccountPane.java
When you add an authlib-injector account (e.g. LittleSkin) to the HMCL, if the username is an email, and the account has multiple players, a dialog will appear for the user to choose a player. This PR forces the title text above this dialog to be uppercase to match the style elsewhere in the launcher.
=> Capitalize choose player dialog title text

HMCL/src/main/resources/assets/openjfx-dependencies.json, javafx.gradle.kts
在 Windows x86-64，Linux x86-64，macOS x86-64/arm64 平台将自动下载的 JavaFX 版本从 19.0.2.1 更新至 17.0.13。
此次更新带来了以下值得注意的优化和修复：
* JDK-8281327: JavaFX does not support fonts installed per-user on Windows 10/11
* JDK-8181084: JavaFX show big icons in system menu on macOS with Retina display
* JDK-8251240: Menus inaccessible on Linux with i3 wm
=> Bump JavaFX to 17.0.13

HMCL/src/main/java/org/jackhuang/hmcl/ui/CrashWindow.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/GameCrashWindow.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/ListPageSkin.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/ToolbarListPageSkin.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AccountListItemSkin.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/FileItem.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/download/InstallersPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/export/ModpackInfoPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/main/MainPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/main/SettingsView.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/profile/ProfileListItemSkin.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/GameListItemSkin.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModListPageSkin.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/WorldExportPageSkin.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/WorldListItemSkin.java
目前代码中存在大量对 `setOnMouseClicked ` 的误用，这导致一些按钮不响应键盘，或者响应非鼠标左键的点击。本 PR 清理了其中一部分代码。
=> 清理对 setOnMouseClicked 的误用

HMCL/src/main/java/org/jackhuang/hmcl/ui/FXUtils.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/HTMLRenderer.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/InstallerItem.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/LogWindow.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/account/CreateAccountPane.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/account/OAuthAccountLoginDialog.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/AdvancedListItem.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/ComponentListCell.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/FontComboBox.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/IconedMenuItem.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/ImagePickerItem.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/OptionToggleButton.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/SpinnerPane.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/TabHeader.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/download/AdditionalInstallersPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/download/InstallersPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/download/VersionsPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/export/ModpackInfoPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/main/MainPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/main/SettingsView.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/profile/ProfileListItemSkin.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/DownloadListPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/DownloadPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/InstallerListPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/VersionIconDialog.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/WorldListItem.java
目前 HMCL 中大量控件响应任何鼠标点击事件（包括中键、返回键等），不符合常规应用的行为，而且和一部分按钮的行为不一致。本 PR 清理了这些代码，让它们只响应鼠标左键单击。
=> 修复部分控件响应任意鼠标按键点击事件的问题

HMCL/src/main/resources/assets/lang/I18N.properties, HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties
Currently, HMCL does not provide variants for languages ​​(e.g. US, UK, etc.). 
For Chinese, there are already descriptions of Simplified (简体) and Traditional (繁體) to distinguish them, so keep them.
=> For language selection, remove all region descriptions

HMCL/src/main/java/org/jackhuang/hmcl/util/i18n/Locales.java
Sort alphabetically by language code.
| IETF Language Tag | HMCL Internal Usage Code | Language Name (Native) | Language Name (English) |
| :---------------: | :----------------------: | :--------------------: | :---------------------: |
|       en-US       |            EN            |        English         |         English         |
|       es-ES       |            ES            |        Español         |         Spanish         |
|       ja-JP       |            JA            |         日本語         |        Japanese         |
|       ru-RU       |            RU            |        Русский         |         Russian         |
|       zh-CN       |          ZH_CN           |        简体中文        |   Simplified Chinese    |
|       zh-TW       |            ZH            |        繁體中文 …
=> Adjust language selection order

HMCL/src/main/java/org/jackhuang/hmcl/setting/Theme.java, HMCL/src/main/resources/assets/css/blue.css
确定该问题由 #3324 造成。不太明白具体为什么，但指定一个无效的字体就能避免这种情况。
=> 修复对话框按钮自行移动的问题

HMCL/src/main/java/org/jackhuang/hmcl/ui/main/AboutPage.java
Fixes #3436
Specify UTF-8 charset when reading `deps.json` file in `AboutPage.java`.
=> 修复 Copyright © 显示为“漏”的bug

build.gradle.kts
There is some controversy over the use of this word. In order to ensure consistency in formal texts, we should unify them to more tried-and-true and commonly used usages.
By checking at build time, it lets the translator or proofreader correct the word on his/her own without any special attention from the reviewer.
=> Check word 其它 → 其他 when checking translation

HMCL/src/main/java/org/jackhuang/hmcl/ui/decorator/DecoratorSkin.java, HMCL/src/main/resources/assets/css/root.css
=> 使用 ONE_PASS_BOX 阴影代替高斯模糊

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/OAuth.java
`interval` 的单位应当是秒，之前的实现错误的把它当做毫秒处理，导致轮询过于频繁。
=> 修复 OAuth 登录时轮询过于频繁的问题

HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java
The amdgpu DDX is missing support for modifiers, causing Zink to fail. Disable DRI3 to workaround this issue.
Link: https://gitlab.freedesktop.org/mesa/mesa/-/issues/10093
=> fix(DefaultLauncher): also set LIBGL_KOPPER_DRI2=1 for Zink mode

HMCL/src/main/java/org/jackhuang/hmcl/ui/download/VersionsPage.java
https://github.com/user-attachments/assets/62dd0324-cae8-4ce8-81ce-03a57535a83e
=> 游戏下载页面添加搜索功能

HMCL/src/main/java/org/jackhuang/hmcl/ui/FXUtils.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/download/VersionsPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/DatapackListPageSkin.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/DownloadListPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModListPageSkin.java
目前在模组列表页中选中模组后，按下 Esc 是不会有任何反应的，因为 [ListView](https://github.com/openjdk/jfx/blob/5b074c4c2b4f539301813322a6589cec28121553/modules/javafx.controls/src/main/java/com/sun/javafx/scene/control/behavior/ListViewBehavior.java#L108) 会处理这个事件，认为是取消编辑，而不论是否处于编辑模式中。
这个 PR 添加了 `FXUtils.ignoreEvent()` 函数，用于忽略掉对特定事件的处理。然后，我们就可以让 ListView 不处理 Esc 按下事件，然后在模组页添加 Esc 处理逻辑（必须让 ListView 忽略掉这个事件，不然就会被它优先处理）。
理论上所有用了 ListView / JFXListView 的地方都会有这个问题，即当焦点在 ListView 中时，按下 Esc 不会触发正常的事件处理（如返回上一页、关闭对话框）。比如在游戏下载页面中，对某个版本按下右键后，焦点就会转移到其上，此时再按 Esc 就毫无反应。但是这个问题比较难以触发，需要讨论是否要处理。
=> 模组列表页中按下 Esc 时取消选中

HMCL/src/main/resources/assets/lang/I18N_zh.properties
Noticed it by chance, checked en-US and zh-CN and they are fine.
This was a mistake in my previous PR, fixing it now.
=> fix(locale): fix zh-tw locale for game crash window buttons

HMCL/src/main/java/org/jackhuang/hmcl/util/i18n/I18n.java, HMCL/src/main/resources/assets/lang/I18N.properties, HMCL/src/main/resources/assets/lang/I18N_es.properties, HMCL/src/main/resources/assets/lang/I18N_ja.properties, HMCL/src/main/resources/assets/lang/I18N_ru.properties, HMCL/src/main/resources/assets/lang/I18N_zh.properties, HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties
- Change to a standard and commonly used format.
- Rename i18n key as it is used in more than one place.
---
<s>目前中文时间格式不加空格更加流行且耐看，所以我去掉了空格。</s>
其他语言我根据 https://github.com/HMCL-dev/HMCL/pull/3608 的效果做了调整。
由于不止在一个地方使用，我重命名了 i18n 键。
=> fix(locale): adjust time formats for various languages

HMCL/src/main/java/org/jackhuang/hmcl/ui/account/OfflineAccountSkinPane.java
The word "LittleSkin" appears twice in OfflineAccountSkinPane, but one of them is hardcoded. Add i18n support for the hardcoded one.
=> fix(i18n): fix a missing i18n for LittleSkin term

HMCLCore/src/main/java/org/jackhuang/hmcl/download/LibraryAnalyzer.java
问题报告：https://www.bilibili.com/video/BV1BzAfewECR
当使用其他启动器安装 Minecraft 1.20.1+NeoForge 47.1.106 的时候，HMCL 会错误的将 NeoForge 版本识别为 47.2.2。
造成该问题的原因是 NeoForge 1.20.1-47.1.106  的 FML 版本是 47.2.2，HMCL 在没有找到 patch 的情况下就会错误地将 FML 版本当成 NeoForge 版本。
NeoForge 的版本号规则过于复杂，我不确定会不会对识别其他版本造成影响，所以该补丁需要更多测试。
=> 修复 NeoForge 版本识别错误的问题

HMCL/src/main/java/org/jackhuang/hmcl/ui/account/OfflineAccountSkinPane.java
make the text around the selector not be covered.
resolves https://github.com/HMCL-dev/HMCL/issues/3296
<details>
<summary>Diff Preview</summary>
BEFORE ___________ AFTER
*Russian*
*Spanish*
</details>
---
研究了好一会。如果解决方式欠妥还请指教。
cc @burningtnt, @Glavo, @yushijinhun, and @zkitefly
=> fix(ui): limit width of FileSelector in offline skin pane

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/microsoft/MicrosoftAccount.java
=> Fix #2048: 当微软账户 Token 过期时应当刷新账户

HMCL/src/main/java/org/jackhuang/hmcl/ui/decorator/DecoratorSkin.java
最小化窗口并恢复后，最小化按钮会保持获取焦点的高亮状态。本 PR 通过禁止该按钮获取焦点避免这种情况。
=> 禁止标题栏按钮获取焦点

HMCL/src/main/java/org/jackhuang/hmcl/ui/animation/TransitionPane.java
略微调整默认动画时间，使其过渡时间是帧间隔的整数倍。
未来还需要继续微调。
=> 优化 TransitionPane

HMCL/src/main/resources/assets/lang/I18N.properties
`settings.launcher.launcher_log.reveal`  
Considering that HMCL is a cross-platform launcher and not all systems use the term `Explorer`, this should be changed to a more generic term.
`update.channel.dev.hint` and `update.channel.nightly.hint`  
Revise text style.
Misc  
Resolve rendering issues on some text editors.
=> chore(locale): revise english

HMCL/src/main/resources/assets/lang/I18N.properties, HMCL/src/main/resources/assets/lang/I18N_es.properties, HMCL/src/main/resources/assets/lang/I18N_ru.properties
Oops... Didn't notice this before.
The issue first appeared in https://github.com/HMCL-dev/HMCL/pull/2468
=> fix(locale): remove duplicate extensions

HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/JFXDialogPane.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/decorator/DecoratorController.java
打开对话框时应当隐藏控件焦点，仅当用户使用 TAB 开始遍历时才应显示焦点。
=> Fix #3694: 显示对话框时隐藏焦点

HMCL/src/main/java/org/jackhuang/hmcl/ui/GameCrashWindow.java
Shows a scroll bar when needed to prevent user misinterpretation when there is too much information.
=> fix: add scrollbar for GameCrashWindow

HMCL/src/main/java/org/jackhuang/hmcl/Main.java
当 HMCL 运行在 JDK 24 上时，由于 [JEP 498](https://openjdk.org/jeps/498)，JavaFX 会引发弃用警告。
本 PR 为 JDK 24/25 抑制了此警告。未来 JavaFX 解决该警告后可以移除相关代码。
=> 消除 JEP 498 引入的弃用警告

HMCL/src/main/java/org/jackhuang/hmcl/ui/account/OfflineAccountSkinPane.java
Fix #https://github.com/HMCL-dev/HMCL/issues/3627
=> Fix #3627 离线账户皮肤界面选择本地皮肤后，切换模型不会使左侧 3D 预览即时生效

HMCL/build.gradle.kts
这样便于开发时切换测试用 Java。尤其是在 #3803 完成后，这将成为开发者使用 Java 8 测试启动器的首选途径。
=> Gradle run task 应使用 HMCL_JAVA_HOME 所指向的 Java

HMCL/src/main/java/org/jackhuang/hmcl/setting/Config.java
不好评价，为人么有人序列化不直接写好class啊……
时间戳反序列化成了double，绝
解决了 https://github.com/HMCL-dev/HMCL/issues/2620#issuecomment-1873171024 提到的重复登录的bug
作为进一步实现临时登录之前的一个小fix
=> fix: serialization

HMCL/build.gradle.kts, HMCL/src/main/java/org/jackhuang/hmcl/setting/Accounts.java, HMCL/src/main/java/org/jackhuang/hmcl/setting/GlobalConfig.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AccountListPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/account/CreateAccountPane.java, HMCL/src/main/resources/assets/lang/I18N.properties, HMCL/src/main/resources/assets/lang/I18N_zh.properties, HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties
当用户未登录微软账户时，禁止用户使用离线账户和外置登录。
默认情况下中国大陆用户不会受到此限制，但用户可以通过 JVM 选项 `-Dhmcl.offline.auth.restricted=true` 主动启用此限制。
=> 默认限制离线账户功能

HMCLCore/build.gradle.kts
https://github.com/google/gson/releases/tag/gson-parent-2.13.0
=> Bump Gson to 2.13.0

HMCLCore/src/main/java/org/jackhuang/hmcl/download/neoforge/NeoForgeOfficialVersionList.java
介于 0.25w14craftmine.3-beta 是 NF 的第一个愚人节版本，我们完全可以直接 ———— 特判！
=> Fix #3825 修复 NeoForge 愚人节版本无法正常解析的问题

HMCLCore/src/main/java/org/jackhuang/hmcl/auth/offline/Skin.java
Fix #3851
访问```https://littleskin.cn/username.json```时默认会重定向至```https://littleskin.cn/csl/username.json```
然而当username包含中文的时候，编码方式不一致，导致无法获取皮肤相关的资料
网站在重定向时使用的编码是ISO_8859_1，而程序中采用的编码是UTF-8
直接访问```https://littleskin.cn/csl/username.json```跳过重定向过程就可以解决这个问题
=> Fix #3851 当用户名为中文名时，离线账户 - LittleSkin 换肤 功能失效

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/DownloadListPage.java
经过实测，原issue复现不需要指定游戏版本，只需要在搜索结果的基础上再搜索就可以复现了
下面是视频，左修复后，右最新HMCL预览版：
https://github.com/user-attachments/assets/ad92c7e2-186d-4e6f-98f3-c911f0b59eda
=> Fix #3864 游戏内容下载的分页按钮不重置

HMCLCore/src/main/java/org/jackhuang/hmcl/download/LibraryAnalyzer.java, HMCLCore/src/main/java/org/jackhuang/hmcl/game/CrashReportAnalyzer.java
使用 https://www.jetbrains.com/help/idea/using-language-injections.html 功能，以移除重复的 `Pattern.compile` 声明
=> 使用 @Language 注解

HMCL/src/main/java/org/jackhuang/hmcl/game/HMCLGameRepository.java
Fix #3218 
在复制version文件夹前补上了黑名单筛选的操作
以确保在选项开启后，存档文件夹不会被复制到新游戏版本
=> Fix #3218: 修复复制游戏版本里的“复制存档”选项失效问题

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/DownloadPage.java
Fix #3896
信息栏没有设置最低高度导致被版本列表挤压，只要是多行信息且版本列表超出界面高度就能复现
將信息栏的高度綁定到```prefHeight(-1)```自动调节
左边为修复前，右边为修复后
=> Fix #3896: 下载界面对于多行信息显示错误

HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AccountListPage.java
Deepin 因为某些原因，在中国大陆地区将时区名称设置为 `Asia/Beijing`，导致 HMCL 未能识别。本 PR 修复了此问题。
=> 修复启动器在部分 Linux 发行版上无法正确识别用户地区的问题

HMCL/src/main/java/org/jackhuang/hmcl/ui/main/LauncherSettingsPage.java
=> Fix #3757 切换游戏文件夹后，全局游戏设置应重新读取设置

HMCLCore/src/main/java/org/jackhuang/hmcl/util/logging/Logger.java
`org.jackhuang.hmcl.` 太长了
```
[21:40:04] [@.Launcher.main/INFO] *** HMCL @develop@ ***
[21:40:04] [@.Launcher.main/INFO] Operating System: Windows 10 10.0.19045
[21:40:04] [@.Launcher.main/INFO] Processor Identifier: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
[21:40:04] [@.Launcher.main/INFO] System Architecture: x86-64
[21:40:04] [@.Launcher.main/INFO] Native Encoding: UTF-8
[21:40:04] [@.Launcher.main/INFO] JNU Encoding: GBK
[21:40:04] [@.Launcher.main/INFO] Code Page: 936
[21:40:04] [@.Launcher.main/INFO] Java Architecture: x86-64
[21:40:04] [@.Launcher.main/INFO] Java Version: 11.0.21, BellSoft
[21:40:04] [@.Launcher.main/INFO] Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), BellSoft
```
=> 将日志 caller 信息中的 'org.jackhuang.hmcl.' 缩短为 '@.'

HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/PromptDialogPane.java
- Limit the dialog width to avoid too long a width
- Avoid accidental blank line in the information box (That blue bg box)
<details>
<summary>Preview</summary>
<br/>
| Before | After |
|--------|--------|
| ![image-1](https://github.com/user-attachments/assets/90ea7af4-36d3-4a9f-8c0e-95b3d3e37686) | ![image-2](https://github.com/user-attachments/assets/4cdc97cc-aa57-4568-a6b8-9d83f44e38a6) |
| ![image-3](https://github.com/user-attachments/assets/4c29c8eb-9ec7-4219-9028-06b26473bf81) | ![image-4](https://github.com/user-attachments/assets/bf53a367-aad8-48c1-b953-fb57cac95915) |
| ![image-5](https://github.com/user-attachments/assets/6502db7e-f434-4e12-8e6a-2918f3b58efd) | ![image-6](https://github.com/user-attachments/assets/34ab4cfa-e89f-49f6-9b54-df0d0b78263e) |
</details>
=> fix(ui): refine PromptDialogPane

HMCL/build.gradle.kts
应该彻底修好 HMCLauncher 无法找到 PATH 中的 Java 的问题了。
=> Bump HMCLauncher to 3.6.0.4

HMCL/src/main/java/org/jackhuang/hmcl/setting/FontManager.java
有时候 `fc-match` 会返回一个 font family 列表，而不是单个 font family 名称。HMCL 应当处理这种情况。
=> 修复部分 Linux 环境中未正确选择默认字体的问题

HMCL/src/main/java/org/jackhuang/hmcl/ui/download/AbstractInstallersPage.java
不知道为什么，使用 JavaFX 25 时中央的 FlowPane 的高度会增加一倍，包装到 ScrollPane 里就好了……
=> Fix #4067: 修复使用 JavaFX 25 启动时下载界面布局错位的问题

HMCL/src/main/resources/assets/lang/I18N.properties, HMCL/src/main/resources/assets/lang/I18N_es.properties, HMCL/src/main/resources/assets/lang/I18N_ru.properties, HMCL/src/main/resources/assets/lang/I18N_zh.properties, HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties
- For Chinese, replace the relevant term with 'Java 虚拟机/虛擬機'.
- For other languages, replace the relevant term with 'JVM'.
- Replace 'JVM' with 'Java' in some cases where 'JVM' is inappropriate.
=> fix(locale): unify terminology usage of 'JVM' and 'Java'

HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/windows/WinReg.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/windows/WindowsGPUDetector.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/windows/WindowsHardwareDetector.java, HMCLCore/src/test/java/org/jackhuang/hmcl/util/platform/windows/WinRegTest.java
检测注册表应当比使用 PowerShell 更快，而且不容易触发安全软件的误报。
=> 在 Windows 平台优先使用注册表探测 GPU

HMCL/src/main/resources/assets/css/root.css
fix(#4166): 新增内存显示条禁用样式
before:
after:
=> fix(#4166): 新增内存显示条禁用样式

HMCL/src/main/java/org/jackhuang/hmcl/ui/image/apng/argb8888/Argb8888Processors.java
本 PR 解决的应该就是 #4205 简介中提到的问题（至少症状是差不多的）
测试文件：[helloface.apng](https://github.com/user-attachments/assets/c0939d3e-1ccc-4249-89f9-61511354995d)（应该需要修改扩展名？）
编码命令行：`ffmpeg -i C:\Windows\SystemApps\Microsoft.Windows.CloudExperienceHost_cw5n1h2txyewy\media\HelloFaceAnimation.gif -plays 0 -pix_fmt rgba64be helloface.apng`
修复前
修复后
我不知道该不该提交上游
=> 修复 APNG Truecolour16Alpha 处理器克隆方法返回类型错误的问题

HMCLCore/src/main/java/org/jackhuang/hmcl/download/game/GameRemoteVersion.java
我上次修的 https://github.com/HMCL-dev/HMCL/pull/4066/ 有个小bug，时间一样应该按照版本号大的来
=> 进一步修复#4063：版本列表排序错误

HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/windows/WindowsGPUDetector.java
#4286 修复Windows启动时注册表项目类型为`REG_BINARY`时输出的GPU信息不正常
=> 修复 Windows 平台 GPU 信息可能显示为"[B@xxx" 的问题

HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/TaskListPane.java
当前 `TaskListPane` 为每个 `Task` 创建一个 `Node`，并使用 `VBox` 存储它们，在处理大量任务时（比如下载游戏）性能极其低下。
本 PR 优化了 `TaskListPane`，将内部控件切换为 `ListView`，使其只需要渲染少量节点，大幅优化了性能。
=> 优化 TaskListPane

HMCL/src/main/java/org/jackhuang/hmcl/ui/Controllers.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/decorator/DecoratorController.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/decorator/DecoratorSkin.java
macOS 对最大化/全屏模式的支持很奇怪。为了避免出现意外行为，我们暂时禁止在 macOS 上进入最大化和全屏模式。
本 PR 合并后我会尽快发布并推送新版本。
=> Fix #4290: 在 macOS 上禁止最大化和全屏模式

HMCL/src/main/java/org/jackhuang/hmcl/setting/VersionSetting.java
目前 `VersionSetting` 会将枚举字段序列化为其 `ordinal`，这导致我们无法随意修改这些枚举中成员的位置。
本 PR 使 `VersionSetting` 在反序列化时能够将以字符串形式存储的字段解析为枚举值，为未来我们修改 `VersionSetting` 中枚举成员的序列化方式做准备。
=> 支持以字符串形式序列化 VersionSetting 中的枚举成员

HMCLCore/src/main/java/org/jackhuang/hmcl/util/io/NetworkUtils.java, HMCLCore/src/test/java/org/jackhuang/hmcl/util/io/NetworkUtilsTest.java
相比 `?`(`%3F`)，U+FFFD (replacement character) 更能明确表示这是一个错误字符。
=> 将 URI 中的错误代理对编码为 U+FFFD

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/WorldInfoPage.java, HMCL/src/main/resources/assets/lang/I18N.properties, HMCL/src/main/resources/assets/lang/I18N_zh.properties, HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties
之前即使世界已经是极限模式，会被显示为生存模式
AI的解释是这样的：
在 Minecraft 的 `level.dat` 里，Hardcore 并不是一个单独的 `GameType`，而是由两个 NBT 字段共同决定的：
* `hardcore` (ByteTag) = 1 → 世界是极限模式
* `playerGameType` (IntTag) = 存储基础模式（通常是 0 = 生存），但 UI 上应显示为 **极限模式**
这个PR修复了这个问题，下拉框添加了极限模式。经过测试，无论是将已存在的世界更改为极限模式还是识别极限极限模式都没有问题。
=> 修复世界管理不支持显示极限模式

HMCLCore/src/main/java/org/jackhuang/hmcl/download/DefaultDependencyManager.java
`GameAssetDownloadTask` 设置了 `hmcl.install.assets` 作为 stage，但启动游戏时我们没有显示该 stage，这会导致 `GameAssetDownloadTask` 显示在 `TaskListPane` 的顶部。我们应该避免这个问题。
=> 启动游戏时隐藏 GameAssetDownloadTask

HMCL/src/main/java/org/jackhuang/hmcl/ui/download/VersionsPage.java, HMCL/src/main/java/org/jackhuang/hmcl/util/i18n/I18n.java, HMCL/src/main/java/org/jackhuang/hmcl/util/i18n/Locales.java, HMCL/src/main/java/org/jackhuang/hmcl/util/i18n/MinecraftWiki.java, HMCL/src/main/resources/assets/lang/I18N.properties, HMCL/src/main/resources/assets/lang/I18N_es.properties, HMCL/src/main/resources/assets/lang/I18N_ja.properties, HMCL/src/main/resources/assets/lang/I18N_lzh.properties, HMCL/src/main/resources/assets/lang/I18N_ru.properties, HMCL/src/main/resources/assets/lang/I18N_uk.properties, HMCL/src/main/resources/assets/lang/I18N_zh.properties, HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties
- 修复中文环境下部分版本无法跳转的问题
- 修复无法正确选择简体/繁体页面的问题
- 支持文言文环境中跳转至[礦藝大典](https://lzh.minecraft.wiki/)
=> 优化 Minecraft Wiki 跳转功能

HMCL/src/main/java/org/jackhuang/hmcl/game/HMCLGameRepository.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/DatapackListPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModListPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/WorldListPage.java
这些 `System.gc()` 是为了解决 Java 8～11 不支持内存 uncommit，导致启动器所占的系统内存不断增大的问题而插入的。
现在我们已经弃用了对 Java 11 的支持，这些调用可以删除了。删除这些 `System.gc()` 调用还能减少  full gc 造成的 UI 卡顿。
=> 删除不必要的 System.gc() 调用

HMCL/src/main/java/org/jackhuang/hmcl/ui/main/DownloadSettingsPage.java
https://github.com/HMCL-dev/HMCL/pull/4153
=> [release/3.6] 修复“下载线程数”的指示器被提示覆盖的问题

HMCL/src/main/java/org/jackhuang/hmcl/Launcher.java, HMCL/src/main/java/org/jackhuang/hmcl/setting/Config.java, HMCL/src/main/java/org/jackhuang/hmcl/setting/ConfigHolder.java, HMCL/src/main/java/org/jackhuang/hmcl/setting/ConfigUpgrader.java, HMCL/src/main/resources/assets/lang/I18N.properties, HMCL/src/main/resources/assets/lang/I18N_zh.properties, HMCL/src/main/resources/assets/lang/I18N_zh_CN.properties
https://github.com/HMCL-dev/HMCL/pull/4414
=> [release/3.6] 检测到配置文件由高版本启动器创建时禁止保存配置文件

HMCL/src/main/java/org/jackhuang/hmcl/ui/FXUtils.java
1. 自动编码 URI 中的特殊字符
2. macOS 上优先使用 `open` 来打开链接（与 `HostServices#showDocument` 行为一致）
=> 优化 FXUtils#openLink

HMCL/src/main/java/org/jackhuang/hmcl/setting/Config.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/gson/EnumOrdinalDeserializer.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/gson/ObservableField.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/gson/RawPreservingObjectProperty.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/gson/RawPreservingProperty.java
本 PR 新创建了一个 `RawPreservingProperty` 接口。
若是反序列化的时候无法反序列化其值，那么该属性会在内部保存原始 json 内容并回退到默认值上。如果整个运行时这个属性没有被其他值覆盖，那么在序列化的时候它会将原始内容原样序列化至 json 文件中。
这项功能对于 enum 字段尤其重要。这使得我们可以新增枚举条目，并且保证新版本中将字段的内容设置为新增项后，使用旧版本启动器保存字段也不会破坏设置。
=> 创建 RawPreservingProperty 接口

HMCLCore/src/main/java/org/jackhuang/hmcl/util/logging/Level.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/logging/LogEvent.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/logging/Logger.java
这个类是为了在 Java 8 中替代 `java.lang.System.Logger.Level` 而引入的，现在我们可以直接使用 `java.lang.System.Logger.Level` 了，所以没有必要保留它。
=> 清理  org.jackhuang.hmcl.util.logging

HMCL/src/main/java/org/jackhuang/hmcl/ui/FXUtils.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AccountAdvancedListItem.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/main/MainPage.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/main/RootPage.java
考虑到账户管理按钮已经支持通过这种方式快速切换账户，让实例管理按钮支持同样的功能能够增强界面的一致性。
=> 支持在“实例管理”按钮上通过滚动滚轮切换游戏实例

HMCL/src/main/java/org/jackhuang/hmcl/ui/InstallerItem.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/download/AbstractInstallersPage.java
https://github.com/HMCL-dev/HMCL/pull/4508
=> [release/3.6] 修复使用 JavaFX 25 时游戏下载界面布局错误的问题

HMCL/src/main/java/org/jackhuang/hmcl/ui/account/AccountAdvancedListItem.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/main/MainPage.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/Lang.java
https://github.com/HMCL-dev/HMCL/pull/4466
=> [release/3.6] 修复滚动切换游戏实例/账户功能

.github/workflows/gradle.yml
现在单个文件过大，下载 GitHub Action 的构建产物时经常非常缓慢。将这些文件拆分至不同文件中可以大大减少下载 GitHub Action 构建产物的时间。
=> GitHub Action 按文件类型分别上传构建产物

HMCLCore/src/main/java/org/jackhuang/hmcl/download/BMCLAPIDownloadProvider.java
https://github.com/HMCL-dev/HMCL/pull/4120
=> [release/3.6] 更新 unlisted-versions-of-minecraft 镜像源地址

HMCL/src/main/java/org/jackhuang/hmcl/ui/construct/OptionToggleButton.java
- Close #4556
`FXUtils#onClicked`  会忽略连点事件
https://github.com/HMCL-dev/HMCL/blob/168c4ac708f5be1039d7ea0667dd5ec7f7dc7d78/HMCL/src/main/java/org/jackhuang/hmcl/ui/FXUtils.java#L1360-L1366
=> Fix #4556 :“在短时间内连续点击“行按钮”不会正常连续更改 是/否”

HMCL/src/main/java/org/jackhuang/hmcl/game/LauncherHelper.java, HMCL/src/main/java/org/jackhuang/hmcl/ui/image/apng/util/PartialInflaterInputStream.java, HMCLCore/src/main/java/org/jackhuang/hmcl/task/Schedulers.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/javafx/BindingMapping.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/javafx/ObservableCache.java, HMCLCore/src/main/java/org/jackhuang/hmcl/util/platform/ManagedProcess.java
有些代码未来可能会切换到虚拟线程。考虑到我们需要兼容 Java 21，为了避免 `synchronized` 块将虚拟线程 pin 在载体线程上，我们需要尽量使用 `ReentrantLock` 替换 `synchronized` 块。
=> 从 synchronized 切换至 ReentrantLock

HMCL/build.gradle.kts, build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/java/org/jackhuang/hmcl/gradle/ci/GitHubActionUtils.java, buildSrc/src/main/java/org/jackhuang/hmcl/gradle/ci/JenkinsUtils.java, buildSrc/src/main/java/org/jackhuang/hmcl/gradle/utils/PropertiesUtils.java, config-jenkins.sh, config/jenkins/config-jenkins.sh, config/jenkins/dev/Jenkinsfile, config/jenkins/stable/Jenkinsfile, config/project.properties
https://github.com/HMCL-dev/HMCL/pull/4559
=> [release/3.6] 更新 Jenkins CI 服务器的发布模型

HMCLCore/src/main/java/org/jackhuang/hmcl/util/i18n/LocaleUtils.java
Fix #4572: Use String::lines to handle line separators on various OS
=> Fix #4572: Use String::lines to handle line separators on various OS

HMCL/src/main/java/org/jackhuang/hmcl/ui/terracotta/TerracottaControllerPage.java
如果陶瓦加入的是旧版房间（legacy、pclce），玩家列表将显示为空。
=> 隐藏空的 Terracotta 玩家列表

HMCL/src/main/java/org/jackhuang/hmcl/ui/versions/ModListPageSkin.java
现在的模组信息对话框会直接占领整个窗口的最大宽度，尤其是近期推出启动器最大化功能后，这个效果太糟糕了
我把对话框的最大宽度限制为启动器窗口宽度的 70%，且高度可以根据模组简介长度自适应，不会对其他短简介的模组造成不良影响。如图
<details>
现在：
修改后：
</details>
以我写的 [Texture Locale Redirector](https://www.curseforge.com/minecraft/mc-mods/texture-locale-redirector) 模组为例，在高度基本不变下简介显示完全了
=> 优化模组信息对话框 UI 宽高

HMCL/src/main/java/org/jackhuang/hmcl/game/LauncherHelper.java, HMCLCore/src/main/java/org/jackhuang/hmcl/game/DefaultGameRepository.java, HMCLCore/src/main/java/org/jackhuang/hmcl/game/GameRepository.java, HMCLCore/src/main/java/org/jackhuang/hmcl/mod/ModManager.java, HMCLCore/src/main/java/org/jackhuang/hmcl/mod/curse/CurseCompletionTask.java, HMCLCore/src/main/java/org/jackhuang/hmcl/mod/mcbbs/McbbsModpackCompletionTask.java
现在 HMCL 会先分析实例已安装的模组加载器，从而解决将同时支持 NeoForge 和 Fabric 的模组总是判定为 NeoForge 模组的问题。
=> 优化模组加载器检测机制
